(function () {
  "use strict";
  const CVVH = window.CVVH = window.CVVH || {};
  const RELATIONSHIP = Object.freeze({ stranger:0, regular:4, familiar:10, friend:22, bestCustomer:40 });

  function dialogue(firstVisit, normal, extra) {
    return Object.freeze(Object.assign({
      firstVisit:[firstVisit],
      normal:Object.freeze(normal),
      highRelationship:["Quầy mình thành điểm hẹn quen rồi đó."],
      fastService:["Nhanh, đúng, nóng giòn. Tuyệt!"],
      slowService:["Không sao, làm đúng là được."],
      wrongOrder:["Hình như đơn này chưa đúng rồi."],
      rain:["Mưa mà có món nóng là đúng bài."],
      exams:["Ăn xong mới đủ sức học tiếp."],
      graduation:["Rời trường rồi vẫn nhớ đường ghé quầy."]
    }, extra || {}));
  }

  function person(data) {
    data.relationship = RELATIONSHIP;
    data.collectible = true;
    data.dialogue = dialogue(data.firstVisit, data.normal, data.extra);
    delete data.firstVisit; delete data.normal; delete data.extra;
    return Object.freeze(data);
  }

  const registry = Object.freeze([
    person({ id:"khanh", name:"Khánh", gender:"male", avatar:"./assets/characters/khanh.svg", ageRole:"Nam sinh mê ẩm thực", personality:"Vui vẻ, tự tin, cực kỳ nghiêm túc với đồ ăn", speakingStyle:"Hào hứng như nhà phê bình ẩm thực", reason:"Thử mọi món và mọi công thức sốt", runningJoke:"Phần rất lớn vẫn chỉ là phần giảm ăn", arc:"Từ khách khó tính thành người giúp quầy xây thực đơn", relations:["duong","quy"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-mix", patienceMultiplier:1.55, portionSizeWeight:"giant", schedule:"invasion", storyEvents:["khanh-second-order","menu-tasting"], firstVisit:"Chị nói thiệt đi, phần này là phần thường hay phần thử lòng người?", normal:["Em không ăn nhiều. Em chỉ ăn đúng nhu cầu.","Bốn phần là giảm rồi.","Một xiên chỉ là lời chào.","Chị cứ chiên, chuyện số lượng để em lo.","Em đã chuẩn bị tinh thần cho khay lớn.","Em tới kiểm tra chất lượng định kỳ.","Món trước ngon nên em quay lại xác minh.","Sốt mix hôm nay phải thật cân bằng.","Phần này thơm, em đánh giá cao.","Em vừa ăn mà vẫn thấy đây là khởi đầu mới."], extra:{ highRelationship:["Chị cứ chọn giúp em, em tin tay nghề quầy mình.","Mai em dẫn cả nhóm qua, nhớ chuẩn bị khay nha."], wrongOrder:["Sai món không đáng sợ. Phần ít mới đáng sợ."], slowService:["Em chờ được, miễn phần cuối đừng nhỏ."] } }),
    person({ id:"nhan", name:"Nhân", gender:"female", avatar:"./assets/characters/nhan.svg", ageRole:"Nữ du học sinh trao đổi từ Hong Kong", personality:"Điềm tĩnh, quan sát kỹ, hài khô", speakingStyle:"Tiếng Việt tốt, đôi lúc so sánh đời sống Việt Nam và Hong Kong", reason:"Khám phá đồ ăn đường phố Việt Nam bằng tinh thần thu thập dữ liệu", runningJoke:"Luôn cần thêm một mẫu thử trước khi kết luận", arc:"Tìm thấy cảm giác thân thuộc ở Biên Hòa", relations:["thay-tung"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.08, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["exchange-notes"], firstVisit:"Ở Hong Kong cũng có fish ball, nhưng kiểu này khác.", normal:["Em cần thêm một mẫu trước khi kết luận.","Độ giòn hôm nay cao hơn hôm qua.","Biên Hòa nóng hơn em tưởng.","Cá viên ở đây có kiểu sốt rất riêng.","Em ghi chú bằng trí nhớ thôi.","Đây là nghiên cứu có thể ăn được.","Em đang học từ lóng qua quầy chị.","Mẫu hôm nay khá thuyết phục.","Em thích cách mọi người ghé rồi kể chuyện.","Cho em thử một tổ hợp khác lần trước."], extra:{ highRelationship:["Quầy chị làm em thấy Biên Hòa quen hơn.","Em sẽ mang công thức sốt này về kể với bạn."], wrongOrder:["Dữ liệu này không khớp đơn em đã gọi."] } }),
    person({ id:"phuoc-nguyen", name:"Phước Nguyên", gender:"male", avatar:"./assets/characters/phuoc-nguyen.svg", ageRole:"Nam sinh đứng đầu lớp", personality:"Học rất giỏi, thông minh, hài khô", speakingStyle:"Chính xác nhưng không khoe khoang", reason:"Ăn xế sau giờ học đội tuyển", runningJoke:"Bài khó giải nhanh, chọn sốt mất lâu hơn", arc:"Học cách nghỉ ngơi cùng bạn thân Anh Quân", relations:["anh-quan","thay-tung"], favoriteFood:"bo-vien", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.12, portionSizeWeight:"normal", schedule:"after-class", storyEvents:["academic-weapon","best-friend-duty"], firstVisit:"Em giải xong đề rồi, giờ tới bài toán chọn sốt.", normal:["Bài khó có đáp án, đói thì có món nóng.","Anh Quân bảo em nghỉ năm phút.","Em không tính calo trong giờ tự thưởng.","Điểm số không giúp chọn được sốt.","Cho em món ít rủi ro cháy nhất.","Em tới đúng giờ, hiếm hơn điểm mười.","Bài hôm nay dễ hơn lời đồn.","Anh Quân chắc sắp tới dọn tình huống.","Em đã nộp bài, giờ não được nghỉ.","Một phần vừa đủ để quay lại học."], extra:{ highRelationship:["Anh Quân là người kéo em ra khỏi bàn học đúng lúc.","Quầy mình là giờ giải lao chính thức của tụi em."] } }),
    person({ id:"anh-quan", name:"Anh Quân", gender:"male", avatar:"./assets/characters/anh-quan.svg", ageRole:"Nam sinh, bạn thân Phước Nguyên", personality:"Thoải mái, nhanh trí, dí dỏm", speakingStyle:"Đùa nhẹ rồi xử lý tình huống rất gọn", reason:"Kéo Phước Nguyên đi nghỉ và giữ nhóm khỏi căng thẳng", runningJoke:"Luôn tới làm DAMAGE CONTROL", arc:"Cho bạn thân thấy nghỉ ngơi không làm giảm thành tích", relations:["phuoc-nguyen","quy"], favoriteFood:"xuc-xich", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.08, portionSizeWeight:"normal", schedule:"after-class", storyEvents:["damage-control","best-friend-duty"], firstVisit:"Phước Nguyên có nói gì nghiêm trọng không? Em tới dọn hiện trường.", normal:["Em phụ trách đưa học sinh giỏi đi ăn.","Bạn em đang suy nghĩ quá nhiều rồi.","DAMAGE CONTROL có phí bằng một xiên nha.","Phước Nguyên chọn sốt xong chưa chị?","Hôm nay em không chữa cháy, chỉ gọi món.","Bài kiểm tra ổn, tinh thần cả nhóm càng ổn.","Cho em món cầm đi tìm bạn.","Em tới sau nhưng order nhanh.","Người giỏi cũng cần giờ nghỉ.","Em xác nhận: ăn trước, phân tích sau."], extra:{ highRelationship:["Tụi em thân từ hồi còn tranh nhau bàn đầu.","Bạn thân là người nhắc mình đóng sách đúng lúc."] } }),
    person({ id:"thien-an", name:"Thiên Ân", gender:"male", avatar:"./assets/characters/thien-an.svg", ageRole:"Nam sinh đường phố, vẻ ngoài dữ", personality:"Thẳng, từng trải nhưng tử tế", speakingStyle:"Ít chữ, nói trực tiếp", reason:"Ghé sau giờ phụ việc và kín đáo trông chừng Homi", runningJoke:"Mặt lạnh nhưng luôn bẻ bánh cho chó ngửi, không cho ăn bậy", arc:"Để mọi người thấy phần mềm bên trong vẻ ngoài cứng", relations:["hoang-linh"], favoriteFood:"nem-chua-ran", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.18, portionSizeWeight:"large", schedule:"late", storyEvents:["tough-outside","homi-soft-side"], firstVisit:"Cho anh phần nóng. Ít nói, nhiều món.", normal:["Làm giòn giúp anh.","Anh chờ được.","Đừng cho Homi ăn đồ chiên nha.","Nó nhìn vậy thôi, anh không mềm lòng đâu.","Cho phần mang về.","Cay vừa, đừng ngọt.","Đường hôm nay đông.","Hoàng Linh đánh trống nghe từ đầu hẻm.","Anh trả đủ, khỏi làm tròn.","Quầy sạch là được."], extra:{ highRelationship:["Homi thấy anh là chạy lại. Đừng kể ai.","Quầy này ổn, anh mới quay lại hoài."], fastService:["Gọn. Được."], wrongOrder:["Không đúng. Làm lại giúp anh."] } }),
    person({ id:"hoang-linh", name:"Hoàng Linh", gender:"male", avatar:"./assets/characters/hoang-linh.svg", ageRole:"Nam sinh chơi trống", personality:"Năng lượng, giàu nhịp điệu", speakingStyle:"Nhanh, dùng âm thanh và nhịp để ví von", reason:"Ăn sau buổi tập ban nhạc", runningJoke:"Gõ nhịp lên mọi mặt bàn", arc:"Mang một buổi diễn nhỏ tới đầu hẻm", relations:["thien-an","an"], favoriteFood:"xuc-xich", dislikedFood:null, preferredSauce:"sot-mix", patienceMultiplier:1.02, portionSizeWeight:"large", schedule:"club", storyEvents:["drum-roll","music-event"], firstVisit:"Cho em phần giòn nghe rôm rốp đúng nhịp nha chị.", normal:["Một hai ba bốn, tới lượt em.","Chảo kêu xèo xèo đúng tempo đó.","Mai tụi em diễn đầu hẻm nha.","Cho em phần có âm thanh giòn nhất.","Em gõ nhẹ thôi, bàn vẫn ổn.","Thiên Ân nghe nhạc mà giả bộ không thích.","Homi vẫy đuôi đúng nhịp luôn.","Tập xong tay mỏi mà bụng còn khỏe.","Đơn này vào điệp khúc được rồi.","Mai khách sẽ đông hơn một nhịp đó chị."], extra:{ fastService:["Chuẩn tempo!"], slowService:["Không sao, coi như đoạn nghỉ."] } }),
    person({ id:"an", name:"An", gender:"male", avatar:"./assets/characters/an.svg", ageRole:"Nam sinh đội bóng rổ, tóc xoăn", personality:"Kỷ luật, thân thiện, tập trung", speakingStyle:"Gọn, tích cực, hay ví với nhịp trận đấu", reason:"Bổ sung năng lượng sau buổi tập bóng rổ", runningJoke:"Bảo gọi vừa đủ rồi thành một khay", arc:"Cân bằng thi đấu, học tập và thời gian với bạn bè", relations:["hoang-linh","duong"], favoriteFood:"bo-vien", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.08, portionSizeWeight:"athlete", schedule:"sports", storyEvents:["full-court"], firstVisit:"Cho em phần vừa nha chị. Vừa của người mới tập xong.", normal:["Tập full court xong đói thật.","Cho em phần phục hồi.","Hôm nay em ném rổ khá ổn.","Món nóng là hết hiệp đúng bài.","Em gọi vừa đủ thôi... chắc ba món.","Đội em lát nữa ghé.","Hoàng Linh gõ nhịp cổ vũ vui ghê.","Cho nhiều bò viên giúp em.","Em phải về giãn cơ nữa.","Trận tới em giữ nhịp tốt hơn."], extra:{ highRelationship:["Thắng trận đầu tiên em mang bóng qua chụp với quầy.","Kỷ luật là tập đúng giờ và ăn đúng bữa."] } }),
    person({ id:"duong", name:"Dương", gender:"male", avatar:"./assets/characters/duong.svg", ageRole:"Nam sinh ngành Công nghệ thông tin", personality:"Năng lượng, vui tính, thích giao lưu", speakingStyle:"Đùa bằng ngôn ngữ công nghệ", reason:"Ăn xế, sửa code và hóng chuyện quanh quán", runningJoke:"Hỏi hôm nay có bạn nào xinh ghé", arc:"Biết tập trung đúng lúc và làm chỗ dựa cho bạn", relations:["thuy","vu","thay-tung"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:.96, portionSizeWeight:"large", schedule:"afternoon", storyEvents:["tech-talk"], firstVisit:"Nay có bạn nào xinh ghé quán không chị?", normal:["Em tới ăn thôi nha, thiệt.","Hôm nay server quầy ổn không chị?","Thủy đâu rồi chị?","Em đang restore system bằng đồ chiên.","Cho em combo ít bug.","Code lỗi nhưng món đừng lỗi.","Latency hôm nay thấp đó.","Em hỏi tình hình quán thôi.","Đây là dependency bắt buộc.","Ăn xong em deploy."], extra:{ wrongOrder:["Sai output rồi chị."], fastService:["Response time đẹp."] } }),
    person({ id:"thuy", name:"Thủy", gender:"male", avatar:"./assets/characters/thuy.svg", ageRole:"Nam sinh IT, bạn cùng lớp Dương", personality:"Hiền, tốt bụng, rất rõ là thích chị Thảo", speakingStyle:"Chân thành, dễ lúng túng khi bị trêu", reason:"Ăn xế và tìm mọi lý do để ghé chị Thảo", runningJoke:"Không ai tin Thủy tới chỉ vì cá viên; ai cũng biết em thích chị Thảo", arc:"Bớt viện cớ và dám nói thẳng lòng mình", relations:["duong","trang","tran"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.16, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["obvious-crush"], firstVisit:"Chị Thảo hôm nay đẹp quá.", normal:["Chị ăn tối chưa?","Em ghé vì nhớ... nhớ cá viên.","Tóc chị hôm nay khác đúng không?","Dương nói em lộ quá.","Em làm poster cho quầy rồi.","Mai chị có bán không?","Chị đứng bếp nóng lắm không?","Em tới ăn thôi nha. Thiệt.","Em phụ chị dọn bảng nha.","Chị nhớ nghỉ một chút đó."], extra:{ highRelationship:["Em tới ăn hay tới gặp chị hả? ...cả hai."], slowService:["Không sao, em ngồi đây với chị được mà."], wrongOrder:["Không sao đâu chị, mình làm lại nha."] } }),
    person({ id:"han", name:"Hân", gender:"female", avatar:"./assets/characters/han.svg", ageRole:"Nữ sinh lớp 12 trầm tính", personality:"Kín đáo, độc lập, sắc sảo", speakingStyle:"Nhẹ, ngắn, biết mình muốn gì", reason:"Có chỗ nghỉ giữa lịch ôn dày", runningJoke:"Nói không đói rồi tự gọi thêm", arc:"Tự tin chọn ngành và đi học xa", relations:["vu"], favoriteFood:"pho-mai-que", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.22, portionSizeWeight:"normal", schedule:"quiet", storyEvents:["major-choice"], firstVisit:"Cho em một phần nhỏ thôi ạ.", normal:["Hôm nay em tự chọn món.","Em vừa nộp hồ sơ ngành em thích.","Ở đây ồn mà dễ chịu.","Em không đói lắm đâu.","Dạ, thêm một món nữa.","Em biết mình muốn học gì rồi.","Vũ có ghé thì cũng kệ nó ạ.","Em ngồi yên năm phút nha.","Món hôm qua ngon lắm.","Cho em mang về một phần."], extra:{ highRelationship:["Nếu đi học xa, em vẫn tự tìm đường về quầy.","Em chọn ngành này vì em muốn, vậy là đủ."] } }),
    person({ id:"vu", name:"Vũ", gender:"male", avatar:"./assets/characters/vu.svg", ageRole:"Nam sinh câu lạc bộ tranh biện", personality:"Lý luận, dí dỏm, vụng khi nhắc Hân", speakingStyle:"Lập luận mọi lựa chọn", reason:"Tranh luận sốt nào ngon nhất", runningJoke:"Bình thường tự nhiên, nhắc Hân là mất ổn định", arc:"Dám nói điều mình thật sự nghĩ với Hân", relations:["han","duong"], favoriteFood:"pho-mai-que", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.02, portionSizeWeight:"normal", schedule:"club", storyEvents:["awkward-confession"], firstVisit:"Em có ba luận điểm chứng minh mayo hợp đồ chiên.", normal:["Hân có ghé chưa chị?","Em hỏi để biết thôi.","Mayo có tính nhất quán cao.","Em xin phản biện sốt mix.","Khẩu vị vẫn cần bằng chứng.","Hân đâu rồi chị?","Hôm nay em không tranh luận.","Một phần củng cố lập trường.","Dương đang đánh tráo khái niệm.","Em sẽ nói thẳng, không cần ba luận điểm."], extra:{ wrongOrder:["Dữ kiện này không hỗ trợ kết luận rồi chị."] } }),
    person({ id:"quy", name:"Quý", gender:"male", avatar:"./assets/characters/quy.svg", ageRole:"Nam sinh luôn trễ", personality:"Vội, vui tính, hay quên", speakingStyle:"Nhanh, liên tục nhìn đồng hồ", reason:"Bữa xế diễn ra trong phút cuối", runningJoke:"Lúc nào cũng còn đúng một phút", arc:"Biết chuẩn bị sớm hơn", relations:["trang","tran","anh-quan"], favoriteFood:"xuc-xich", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:.75, portionSizeWeight:"normal", schedule:"late", storyEvents:["one-minute-left"], firstVisit:"Chị làm nhanh, em còn đúng một phút!", normal:["Em không trễ, đồng hồ chạy sớm.","Cho em món cầm chạy được.","Chuông sắp đánh rồi.","Trang với Trân tới chưa?","Hôm nay em sớm hơn hai giây.","Tiết sau tầng ba.","Sốt ít thôi, chạy nó văng.","Bạn em giữ cửa chắc vậy.","Em đã tính đường ngắn nhất.","Một ngày nào đó em sẽ ăn ngồi."] }),
    person({ id:"trang", name:"Trang", gender:"female", avatar:"./assets/characters/trang.svg", ageRole:"Nữ sinh hoạt bát", personality:"Thẳng, nhanh nhẹn, tinh ý", speakingStyle:"Tự nhiên, hay hỏi về hội bạn", reason:"Gặp Quý và Trân sau giờ học", runningJoke:"Group ba người nhưng không ai đọc tin", arc:"Giữ bộ ba gắn bó khi sắp tốt nghiệp", relations:["quy","tran","thuy"], favoriteFood:"nem-chua-ran", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.05, portionSizeWeight:"normal", schedule:"recess", storyEvents:["best-friends"], firstVisit:"Trân nói đây là quầy bí mật ngon nhất khúc này.", normal:["Trân tới chưa chị?","Quý lại còn một phút hả?","Ba đứa em có group mà.","Hôm nay em ăn một mình.","Em chưa tin Trân chưa ăn trước.","Cho em phần mang đi tìm hai đứa kia.","Group im mà quầy đông ghê.","Thủy lại ghé hả chị?","Tụi em sắp tới cùng nhau.","Sốt cay giúp em tỉnh."] }),
    person({ id:"tran", name:"Trân", gender:"female", avatar:"./assets/characters/tran.svg", ageRole:"Nữ sinh lém lỉnh", personality:"Tình cảm, nhanh trí", speakingStyle:"Nhỏ giọng khi đang giấu chuyện", reason:"Thường ăn trước rồi mới gọi bạn", runningJoke:"Bí mật tồn tại khoảng ba phút", arc:"Biết trân trọng những chiều cuối cấp", relations:["quy","trang","thuy"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.06, portionSizeWeight:"normal", schedule:"recess", storyEvents:["secret-keeper"], firstVisit:"Lát Trang hỏi thì chị đừng nói em ăn trước nha.", normal:["Chuyện này đừng lên group nha.","Quý với Trang chưa tới đúng không?","Em mua cho bạn nên không tính.","Em không giấu gì hết.","Chị nhớ bí mật nha.","Một phần thôi, trước khi hai đứa tới.","Group lại đang cãi chỗ gặp.","Em biết Trang sẽ đoán ra.","Thủy nhờ gì chị không?","Cho em món nhanh nhất."] }),
    person({ id:"hoc", name:"Học", gender:"male", avatar:"./assets/characters/hoc.svg", ageRole:"Nam sinh hay trì hoãn", personality:"Tinh nghịch, thông minh, sát deadline", speakingStyle:"Biện minh trôi chảy cho việc chưa học", reason:"Nạp năng lượng trước khi bắt đầu học", runningJoke:"Tên là Học nhưng câu trả lời thường là chưa", arc:"Nghiêm túc hơn trong tuần thi", relations:["quy","khanh"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:.98, portionSizeWeight:"normal", schedule:"late", storyEvents:["study-pending"], firstVisit:"Em đang nạp năng lượng để học.", normal:["Ăn xong em học thiệt.","Sách ở trong cặp rồi.","Em đang tối ưu lịch ôn.","Đây là giờ nghỉ trước khi bắt đầu.","Quý rủ em, em vô tội.","Cho em phần tạo động lực.","Hôm nay em đã mở sách.","Điện thoại tự mở đó chị.","Tuần thi em nghiêm túc.","Chị đừng hỏi bài, hỏi món thôi."] }),
    person({ id:"tho", name:"Thơ", gender:"female", avatar:"./assets/characters/tho.svg", ageRole:"Cán bộ an toàn thực phẩm hư cấu", personality:"Chuyên nghiệp, điềm tĩnh", speakingStyle:"Lịch sự, ngắn gọn", reason:"Kiểm tra khu bán hàng rồi thành khách quen", runningJoke:"Tới ăn nhưng Thảo vẫn tưởng bị kiểm tra", arc:"Từ người kiểm tra thành người hướng dẫn", relations:["chu-sau","chi-hong"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:1.35, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["food-safety"], firstVisit:"Chào em. Chị kiểm tra một chút.", normal:["Hôm nay chị tới ăn.","Khu chế biến sạch đó.","Nhớ thay dầu đúng lúc.","Rác gọn rồi, tốt.","Đồ sống chín để riêng nhé.","Em đừng căng thẳng.","Chị đi ngang nên ghé.","Cho ít cay giúp chị.","Quầy đông vẫn giữ gọn nha.","Hôm nay không kiểm tra."] }),
    person({ id:"thay-minh", name:"Thầy Minh", gender:"male", avatar:"./assets/characters/thay-minh.svg", ageRole:"Hiệu trưởng hư cấu", personality:"Trang trọng, quan tâm kín đáo", speakingStyle:"Chậm, chuẩn", reason:"Quan sát khu vực rồi bí mật gọi món", runningJoke:"Luôn nói chỉ đi kiểm tra", arc:"Công nhận quầy là một phần ký ức học sinh", relations:["co-lan"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.3, portionSizeWeight:"normal", schedule:"late", storyEvents:["inspection"], firstVisit:"Thầy chỉ quan sát khu vực thôi.", normal:["Cho thầy một phần.","Giữ lối đi thông thoáng nhé.","Học sinh quý quầy này lắm.","Thầy không tham gia cạnh tranh.","Cho ít cay thôi.","Hôm nay thầy đi ngang.","Bảng giá rõ ràng, tốt.","Các em ăn xong nhớ vào lớp.","Quầy sạch sẽ đó.","Thầy mang về phòng giáo viên."] }),
    person({ id:"co-lan", name:"Cô Lan", gender:"female", avatar:"./assets/characters/co-lan.svg", ageRole:"Phó hiệu trưởng hư cấu", personality:"Chính xác, nhanh, quan tâm kín đáo", speakingStyle:"Con số rõ ràng, câu ngắn", reason:"Đặt phần cho giáo viên làm muộn", runningJoke:"Quay lại sau đúng bảy phút", arc:"Từ kiểm tra bảng giá thành khách nhóm", relations:["thay-minh","co-linh"], favoriteFood:null, dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.25, portionSizeWeight:"group", schedule:"late", storyEvents:["exactly-on-time"], firstVisit:"Cho cô ba phần. Cô quay lại sau bảy phút.", normal:["Bảy phút rồi.","Cho cô đơn rõ từng món.","Phòng giáo viên còn ba người.","Cô đã tính đủ số phần.","Làm đúng trước, nhanh sau.","Hôm nay cô có tám phút.","Bảng giá mới dễ đọc.","Cho sốt tách riêng.","Cô mang về họp.","Đúng giờ nhé em."] }),
    person({ id:"thay-phong", name:"Thầy Phong", gender:"male", avatar:"./assets/characters/thay-phong.svg", ageRole:"Giáo viên Toán hư cấu", personality:"Logic, tỉnh, hài khô", speakingStyle:"Đo lường và hỏi xác suất", reason:"Tính tỷ lệ giá trên độ ngon", runningJoke:"Đòi con số chính xác cho nhận xét đời thường", arc:"Chấp nhận có thứ không cần tối ưu tuyệt đối", relations:["thay-tung","co-linh"], favoriteFood:"bo-vien", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.24, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["probability"], firstVisit:"Xác suất món của thầy bị cháy là bao nhiêu?", normal:["Thấp là bao nhiêu phần trăm?","Cho thầy một tổ hợp cân bằng.","Ba món có quá nhiều không?","Dữ kiện hôm nay khá thơm.","Tỷ lệ sốt này hợp lý.","Thầy chọn ngẫu nhiên có điều kiện.","Một phần là mẫu nhỏ.","Hai phần tăng độ tin cậy.","Quầy đông theo cấp số nhân.","Kết quả này chấp nhận được."] }),
    person({ id:"co-linh", name:"Cô Linh", gender:"female", avatar:"./assets/characters/co-linh.svg", ageRole:"Giáo viên tiếng Anh hư cấu", personality:"Vui vẻ, gần gũi, tinh tế", speakingStyle:"Chèn cụm tiếng Anh ngắn tự nhiên", reason:"Ăn nhẹ sau giờ dạy", runningJoke:"Spicy, nhưng luôn thêm not too spicy", arc:"Giúp học sinh bớt sợ nói sai", relations:["co-lan","thay-phong"], favoriteFood:"pho-mai-que", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.25, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["english-club"], firstVisit:"Cho cô một phần. Spicy but not too spicy nha.", normal:["One portion, please.","Hôm nay cô nói tiếng Việt thôi. Maybe.","Cho cô món crispy nhất.","Not too spicy nha em.","Sai một từ không sao.","Very popular hôm nay.","Cho cô mang về một phần.","Good smell, good timing.","Cô không kiểm tra từ vựng đâu.","Perfect, cho cô đơn ngẫu nhiên."] }),
    person({ id:"thay-tung", name:"Thầy Tùng", gender:"male", avatar:"./assets/characters/thay-tung.svg", ageRole:"Giáo viên Tin hư cấu", personality:"Ít lời, tinh ý, hài nhẹ", speakingStyle:"Ngắn, đúng trọng tâm", reason:"Ăn sau giờ coi phòng máy", runningJoke:"Code lỗi thì ăn xong sửa", arc:"Âm thầm hỗ trợ học sinh đội tuyển", relations:["phuoc-nguyen","nhan","duong"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.3, portionSizeWeight:"normal", schedule:"late", storyEvents:["debug-later"], firstVisit:"Code lỗi à? Ăn xong sửa.", normal:["Cho thầy một phần.","Máy treo, người không nên treo.","Dương lại hỏi linh tinh hả?","Phước Nguyên học đủ rồi.","Nhân thích nghi nhanh đó.","Mayo. Không cần giải thích.","Phòng máy vừa đóng.","Ăn rồi debug tiếp.","Đơn này không cần refactor.","Gọn là tốt."] }),
    person({ id:"co-huong", name:"Cô Hương", gender:"female", avatar:"./assets/characters/co-huong.svg", ageRole:"Phụ huynh chờ đón con", personality:"Cởi mở, tốt bụng", speakingStyle:"Thân tình", reason:"Đứng chờ con rồi quen cả quầy", runningJoke:"Nói chỉ đứng chờ rồi mua hai phần", arc:"Thành cầu nối phụ huynh–học sinh", relations:["chu-thanh"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-ngot", patienceMultiplier:1.35, portionSizeWeight:"group", schedule:"dismissal", storyEvents:["waiting-parent"], firstVisit:"Cô đứng chờ con thôi.", normal:["Thôi cho cô một phần.","Con cô sắp tan rồi.","Cho cô mang về hai phần.","Quầy hôm nay đông ha.","Mấy đứa nhỏ quý em lắm.","Ít cay giúp cô.","Cô đứng đây mát hơn.","Cho thêm một phần nữa.","Con cô nói món này ngon.","Cô chờ được."] }),
    person({ id:"chu-thanh", name:"Chú Thành", gender:"male", avatar:"./assets/characters/chu-thanh.svg", ageRole:"Phụ huynh nghiêm ngoài mặt", personality:"Thực tế, thương con", speakingStyle:"Nói lý trước rồi đổi ý", reason:"Đón con và mua thêm phần", runningJoke:"Món chiên không tốt... cho chú hai phần", arc:"Bớt khắt khe với những niềm vui nhỏ", relations:["co-huong"], favoriteFood:"nem-chua-ran", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.2, portionSizeWeight:"group", schedule:"dismissal", storyEvents:["one-exception"], firstVisit:"Mấy món chiên ăn nhiều không tốt.", normal:["Cho chú hai phần.","Một phần cho con chú.","Ít sốt thôi.","Hôm nay ngoại lệ.","Quầy sạch thì được.","Con chú sắp ra.","Cho gói kỹ giúp chú.","Chú chỉ nếm thử thôi.","Phần kia cũng cho chú à?","Mai chắc chú không mua."] }),
    person({ id:"chu-sau", name:"Chú Sáu", gender:"male", avatar:"./assets/characters/chu-sau.svg", ageRole:"Bảo vệ trường hư cấu", personality:"Thân thiện, biết nhịp cả khu phố", speakingStyle:"Giọng miền Nam tự nhiên", reason:"Trông cổng và báo trước giờ cao điểm", runningJoke:"Dự báo Khánh tới gần như luôn đúng", arc:"Trở thành người đỡ đầu của quầy", relations:["quy","khanh","tho"], favoriteFood:"xuc-xich", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.4, portionSizeWeight:"normal", schedule:"all-day", storyEvents:["rush-forecast"], firstVisit:"Bán gần đây hả con? Giữ sạch là tụi nhỏ nhớ à.", normal:["Chút nữa Khánh chạy tới cho coi.","Chiều coi bộ mưa à nghen.","Quý lại chạy kìa.","Cho chú một xiên.","Hôm nay tan học sớm.","Kéo bạt sẵn đi con.","Tụi nhỏ quen quầy rồi đó.","Chú canh cổng, con canh chảo.","Mùi này bay tới tận phòng bảo vệ.","Bán tử tế là được."] }),
    person({ id:"chi-hong", name:"Chị Hồng", gender:"female", avatar:"./assets/characters/chi-hong.svg", ageRole:"Chủ quầy bên cạnh", personality:"Cạnh tranh vui vẻ, thực tế", speakingStyle:"Thẳng nhưng không ác ý", reason:"Nghiên cứu thị trường rồi thành đối tác", runningJoke:"Nghiên cứu ba ngày liên tục", arc:"Từ đối thủ thành người hợp tác lúc đông", relations:["tho","chu-sau"], favoriteFood:"banh-trang-tron", dislikedFood:null, preferredSauce:"sot-mix", patienceMultiplier:1.14, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["market-research"], firstVisit:"Mới bán hả? Khúc này khách khó lắm đó.", normal:["Chị đang nghiên cứu thị trường.","Ba ngày chưa đủ dữ liệu.","Khách em đông ghê.","Cho chị thử món mới.","Bên chị hôm nay cũng ổn.","Đối thủ chứ không phải kẻ thù.","Thi tốc độ không em?","Hết bánh tráng thì gọi chị.","Cho sốt mix.","Mai chị nghiên cứu tiếp."] }),
    person({ id:"bac-tu", name:"Bác Tư", gender:"female", avatar:"./assets/characters/bac-tu.svg", ageRole:"Người dân trong xóm", personality:"Ấm áp, tinh ý", speakingStyle:"Chậm, thân tình", reason:"Đi bộ chiều rồi ghé mua cho cháu", runningJoke:"Nói mua cho cháu nhưng nếm trước", arc:"Kể lại những đổi thay của khúc đường", relations:["chu-sau","co-huong"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.45, portionSizeWeight:"group", schedule:"early", storyEvents:["neighborhood-memory"], firstVisit:"Khúc này lâu rồi mới có quầy vui vậy.", normal:["Cho bác phần mang về.","Cháu bác thích cá viên.","Bác nếm một miếng thôi.","Đường này thay đổi nhiều.","Chú Sáu kể bác nghe rồi.","Ít cay giúp bác.","Quầy sạch sẽ đó con.","Bác đi bộ ngang qua.","Cho thêm một phần.","Mai bác lại ghé."] }),
    person({ id:"anh-bon-ba-bay", name:"Anh 4:37", gender:"male", avatar:"./assets/characters/mystery.svg", ageRole:"Cựu học sinh bí ẩn", personality:"Kín tiếng, đúng giờ", speakingStyle:"Ngắn, luôn nhìn đồng hồ", reason:"Trở lại nơi từng chờ người bạn cũ", runningJoke:"Xuất hiện gần đúng 4:37", arc:"Tiết lộ mình là cựu học sinh", relations:["chu-sau","chi-hong"], favoriteFood:"ca-vien-curry", dislikedFood:null, preferredSauce:"sot-mix", patienceMultiplier:1.4, portionSizeWeight:"large", schedule:"late", storyEvents:["mystery"], firstVisit:"Cho anh phần như hôm qua... à, hôm nay là lần đầu.", normal:["Bốn giờ ba mươi bảy.","Anh tới sớm một phút.","Vẫn tổ hợp ngẫu nhiên.","Chú Sáu còn ở đây à?","Khúc đường thay đổi nhiều.","Mùi đồ chiên thì không đổi.","Cho anh thêm sốt mix.","Hôm nay anh ghé nhanh.","Một ngày nào đó anh kể.","Mưa xuống y như hồi đó."] })
  ]);

  const mascot = Object.freeze({
    id:"homi", name:"Homi", avatar:"./assets/characters/homi.svg", collectible:true, isMascot:true,
    personality:"Corgi chân ngắn, tai lớn, chuyên trực quầy và vẫy đuôi đúng lúc.",
    runningJoke:"Không gọi món và tuyệt đối không ăn đồ chiên của khách.",
    dialogue:{ normal:["Gâu!","Homi nghiêng đầu.","Homi vẫy đuôi liên tục."] }
  });

  const genericVariants = Object.freeze([
    Object.freeze({ id:"generic-student-a", name:"Bạn học sinh", gender:"female", avatar:"./assets/characters/generic-student-a.svg", isGeneric:true, patienceMultiplier:1, portionSizeWeight:"normal", preferredSauce:null, favoriteFood:null, dialogue:dialogue("Cho mình một phần nha.",["Cho mình món nóng nha.","Ít cay giúp mình.","Mình đang vội một chút."]) }),
    Object.freeze({ id:"generic-student-b", name:"Bạn học sinh", gender:"male", avatar:"./assets/characters/generic-student-b.svg", isGeneric:true, patienceMultiplier:.95, portionSizeWeight:"normal", preferredSauce:null, favoriteFood:null, dialogue:dialogue("Cho mình gọi món với.",["Cho mình phần mang đi.","Món nào giòn nhất vậy?","Mình chờ được."]) }),
    Object.freeze({ id:"generic-neighbor", name:"Khách trong xóm", gender:"female", avatar:"./assets/characters/generic-neighbor.svg", isGeneric:true, patienceMultiplier:1.2, portionSizeWeight:"normal", preferredSauce:null, favoriteFood:null, dialogue:dialogue("Cho cô một phần nha.",["Ít cay giúp cô.","Cô mua mang về.","Quầy thơm quá nên cô ghé."]) }),
    Object.freeze({ id:"generic-worker", name:"Khách tan ca", gender:"male", avatar:"./assets/characters/generic-worker.svg", isGeneric:true, patienceMultiplier:1.1, portionSizeWeight:"large", preferredSauce:null, favoriteFood:null, dialogue:dialogue("Cho anh phần nóng nha.",["Anh vừa tan ca.","Cho phần no một chút.","Anh mang đi nhé."]) })
  ]);

  function stage(points) {
    if (points >= 40) return "BEST CUSTOMER";
    if (points >= 22) return "FRIEND";
    if (points >= 10) return "FAMILIAR";
    if (points >= 4) return "REGULAR";
    return "STRANGER";
  }
  function stageLabel(value) {
    return { "STRANGER":"Khách mới", "REGULAR":"Khách quen", "FAMILIAR":"Thân thuộc", "FRIEND":"Bạn của quầy", "BEST CUSTOMER":"Khách ruột" }[value] || "Khách mới";
  }
  function pickDialogue(character, context, save) {
    const pool = character.dialogue[context] && character.dialogue[context].length ? character.dialogue[context] : character.dialogue.normal;
    const key = character.id + ":" + context;
    const previous = Number(save.story.dialogueSeen[key]);
    let index = Math.floor(Math.random() * pool.length);
    if (pool.length > 1 && index === previous) index = (index + 1) % pool.length;
    save.story.dialogueSeen[key] = index;
    return pool[index];
  }
  function getById(id) { return registry.find(function (character) { return character.id === id; }); }
  function getCollectibleById(id) { return id === mascot.id ? mascot : getById(id); }

  CVVH.Characters = {
    all:registry, mascot:mascot, genericVariants:genericVariants, getById:getById,
    getCollectibleById:getCollectibleById, stage:stage, stageLabel:stageLabel, pickDialogue:pickDialogue
  };
})();
