(function () {
  "use strict";
  const CVVH = window.CVVH = window.CVVH || {};

  const CANON_OVERRIDES = {
    nhan:{ ageRole:"Nữ du học sinh trao đổi từ Hong Kong", personality:"Điềm tĩnh, quan sát kỹ, hài khô", speakingStyle:"Tiếng Việt tốt, đôi lúc so sánh đời sống Việt Nam và Hong Kong", reason:"Khám phá đồ ăn đường phố Việt Nam bằng tinh thần thu thập dữ liệu", runningJoke:"Luôn cần thêm một mẫu thử trước khi kết luận", relations:["thay-tung"] },
    duong:{ ageRole:"Sinh viên ngành Công nghệ thông tin", personality:"Năng lượng, vui tính, thân thiện", speakingStyle:"Đùa bằng ngôn ngữ công nghệ và đôi khi hỏi hôm nay có bạn nào xinh ghé", reason:"Ăn xế, sửa code và thu thập tin vui quanh quán", runningJoke:"Hỏi tình hình quán nhưng không phải tình hình cá viên", relations:["khanh","thay-tung"] },
    thuy:{ ageRole:"Nam sinh học Công nghệ thông tin, bạn cùng lớp Dương", personality:"Hiền, tốt bụng, rất rõ là thích chị Thảo", speakingStyle:"Chân thành, dễ lúng túng khi bị Dương hoặc Thảo trêu", reason:"Ăn xế, giúp việc lặt vặt và tìm mọi lý do để ghé chị Thảo", runningJoke:"Không ai còn tin Thủy tới quán chỉ vì cá viên; ai cũng biết em thích chị Thảo", relations:["duong","trang","tran"] },
    "co-thao":{ name:"Cô Diệp", ageRole:"Giáo viên kỹ năng hư cấu", personality:"Vui vẻ, nhanh nhẹn, hay khích lệ", speakingStyle:"Nói gọn và luôn kéo học sinh về điều tích cực" },
    quy:{ relations:["trang","tran","khanh","chu-sau"] },
    han:{ relations:["an","vu"] },
    vu:{ relations:["han","duong"] }
  };

  function npc(data) {
    Object.assign(data, CANON_OVERRIDES[data.id] || {});
    data.relationship = { stranger: 0, regular: 4, familiar: 10, friend: 22, bestCustomer: 40 };
    return Object.freeze(data);
  }

  const allCharacters = [
    npc({ id:"khanh", name:"Khánh", avatar:"./assets/characters/khanh.svg", ageRole:"Học sinh mê ẩm thực", personality:"Vui vẻ, tự tin, cực kỳ nghiêm túc với đồ ăn", speakingStyle:"Hào hứng như nhà phê bình ẩm thực", reason:"Thử mọi món và mọi công thức sốt", runningJoke:"Luôn khẳng định phần rất lớn chỉ là phần giảm ăn", arc:"Từ khách khó tính thành người giúp quầy xây thực đơn", relations:["duong","quy"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-mix", patienceMultiplier:1.15, portionSizeWeight:"high", schedule:"recess", storyEvents:["khanh-second-order","menu-tasting"], dialogue:{
      firstVisit:["Chị nói thiệt đi, phần này là phần thường hay phần thử lòng người?"],
      normal:["Em không ăn nhiều. Em chỉ ăn đúng nhu cầu.","Khoan, sốt hôm nay pha khác hôm qua đúng không?","Em đang giảm ăn rồi đó chị.","Bốn phần là giảm rồi.","Phần này thơm. Em đánh giá cao sự nghiêm túc.","Cho em món nào giòn nhất hôm nay.","Em tới kiểm tra chất lượng định kỳ.","Một xiên chỉ là lời chào, chưa phải bữa ăn.","Chị cứ chiên, chuyện số lượng để em lo.","Em đã chuẩn bị tinh thần cho khay lớn.","Mùi này làm em quên luôn tiết sau.","Sốt mix phải cân bằng, không được thiên vị.","Dương no rồi, còn em thì mới khởi động.","Em ăn tiếp để món trước không cô đơn.","Hôm nay quầy đạt chuẩn Khánh."],
      highRelationship:["Chị cứ chọn giúp em, em tin tay nghề quầy mình.","Mai em dẫn cả nhóm qua, nhớ chuẩn bị tinh thần nha."], fastService:["Nhanh vậy? Em chưa kịp phân tích mùi thơm."], slowService:["Em kiên nhẫn được, miễn phần cuối đừng nhỏ."], wrongOrder:["Sai món không đáng sợ. Phần ít mới đáng sợ."], rain:["Trời mưa mà đồ chiên nóng là đúng bài."], exams:["Thi xong em cần một phần mang tính phục hồi."], graduation:["Mai không còn tan học ở đây nữa, nhưng em vẫn biết đường quay lại."]
    }}),
    npc({ id:"nhan", name:"Nhân", avatar:"./assets/characters/nhan.svg", ageRole:"Học sinh đội tuyển Tin", personality:"Tập trung, khô hài, thích tối ưu", speakingStyle:"Câu ngắn, ví von lập trình", reason:"Nạp năng lượng trước giờ luyện thuật toán", runningJoke:"Mọi vấn đề ở quầy đều là bug hoặc feature", arc:"Học cách nghỉ ngơi và làm việc nhóm trước cuộc thi", relations:["thay-tung","tram"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:.95, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["code-contest"], dialogue:{
      firstVisit:["Cho em một phần. Input ít, output giòn."], normal:["Đơn này độ phức tạp O một.","Chảo đầy là stack overflow hả chị?","Mayo là đáp án tối ưu.","Em vừa sửa bug bằng cách... ăn trước.","Cho em chạy lại đơn cũ với dữ liệu mới.","Đợi món chín là blocking operation.","Hôm nay latency của quầy thấp đó.","Em không im lặng, em đang compile.","Cá viên này pass test.","Nếu cháy thì rollback được không?","Một phần đủ để debug tới tối.","Em chọn sốt bằng thuật toán tham lam.","Queue khách hôm nay hơi dài.","Đây là snack, không phải dependency.","Code lỗi nhưng món đừng lỗi nha chị."], highRelationship:["Quầy mình là checkpoint sau mỗi buổi luyện.","Thi xong em viết trang đặt món cho chị, bản không bug... chắc vậy."], fastService:["Response time đẹp."], slowService:["Timeout rồi nhưng em retry được."], wrongOrder:["Output không khớp expected output rồi chị."], rain:["Mưa là ngoại lệ chưa được catch."], exams:["Não em đang 99% CPU."], graduation:["Rời trường nhưng repo kỷ niệm vẫn còn."]
    }}),
    npc({ id:"tram", name:"Trâm", avatar:"./assets/characters/tram.svg", ageRole:"Lớp trưởng", personality:"Gọn gàng, có trách nhiệm, quan tâm tập thể", speakingStyle:"Rõ ràng, lịch sự, theo danh sách", reason:"Thường mua giúp cả lớp", runningJoke:"Đơn ăn vặt cũng có bảng phân công", arc:"Bớt ôm hết việc và biết nhờ bạn bè", relations:["nhan","co-lan"], favoriteFood:"pho-mai", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.12, portionSizeWeight:"group", schedule:"recess", storyEvents:["class-order"], dialogue:{
      firstVisit:["Cho em ba phần, em đọc từng phần để chị khỏi nhầm nha."], normal:["Em đã chốt số lượng với lớp rồi.","Phần này của tổ một, phần kia tổ hai.","Chị cho em xin hóa đơn miệng cũng được.","Em quay lại đúng giờ nha.","Danh sách đổi phút cuối, em xin lỗi chị.","Ai chưa chuyển khoản thì tự chịu.","Em kiểm lại: món, sốt, số lượng. Đủ.","Lớp em họp mà đồ ăn là họp nhanh lắm.","Cho em tách sốt rõ giúp nha chị.","Hôm nay em chỉ mua cho mình. Hiếm lắm đó.","Cả lớp bình chọn quầy chị thắng.","Em đã ghi quỹ ăn vặt riêng rồi.","Chị làm từ từ nhưng đúng giúp em.","Có bạn đổi ý, nhưng em không đổi đơn nữa đâu.","Xong đơn này em mới được nghỉ."], highRelationship:["Chị biết khẩu vị lớp em còn rõ hơn em.","Ngày cuối năm lớp em đặt quầy mình nha."], fastService:["Đúng giờ, đúng món. Tuyệt đối đạt."], slowService:["Em có dự phòng ba phút, vẫn ổn."], wrongOrder:["Mình đối chiếu lại từng món nha chị."], rain:["Em gom đơn để các bạn khỏi chạy mưa."], exams:["Em lập lịch ôn rồi, nhưng chưa lập lịch ngủ."], graduation:["Cuốn sổ lớp trưởng hết trang, còn quầy mình thì em nhớ mãi."]
    }}),
    npc({ id:"quy", name:"Quý", avatar:"./assets/characters/quy.svg", ageRole:"Học sinh luôn trễ", personality:"Vội vàng, vui tính, hay quên", speakingStyle:"Nhanh, đứt quãng, liên tục nhìn đồng hồ", reason:"Bữa xế luôn diễn ra trong 30 giây cuối", runningJoke:"Lúc nào cũng còn đúng một phút", arc:"Cuối cùng biết chuẩn bị sớm cho kỳ thi", relations:["khanh","chu-sau"], favoriteFood:"xuc-xich", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:.72, portionSizeWeight:"normal", schedule:"late", storyEvents:["one-minute-left"], dialogue:{
      firstVisit:["Chị làm nhanh giùm em, còn đúng một phút!"], normal:["Còn bốn mươi giây, kịp mà ha chị?","Em không trễ, đồng hồ chạy sớm.","Nhanh nha chị, trống sắp đánh rồi.","Cho em món cầm chạy được.","Sốt ít thôi, chạy nó văng.","Em đã tính đường ngắn nhất về lớp.","Hôm nay em tới sớm hơn hôm qua hai giây.","Chú Sáu đừng nhìn em, em biết rồi.","Em hứa mai đi sớm. Hứa lần nữa.","Chị gói tinh thần khẩn cấp giúp em.","Tiết sau ở tầng ba. Khó rồi.","Em vừa chạy từ cổng bên kia qua đó.","Cho em đơn có tốc độ cao nhất.","Bạn em giữ cửa... chắc vậy.","Một ngày nào đó em sẽ ăn ngồi."], highRelationship:["Chị thấy chưa, hôm nay em còn hẳn ba phút.","Tốt nghiệp rồi chắc em hết trễ... chắc thôi."], fastService:["Cứu một mạng đi học đúng giờ!"], slowService:["Chuông rồi. Thôi ăn vẫn quan trọng."], wrongOrder:["Sai rồi chị, mà giờ em cũng không kịp cãi."], rain:["Mưa làm kế hoạch chạy của em phá sản."], exams:["Em tới trễ cả buổi ôn, đừng kể lớp trưởng."], graduation:["Lần đầu em không cần chạy vào cổng nữa."]
    }}),
    npc({ id:"an", name:"An", avatar:"./assets/characters/an.svg", ageRole:"Thành viên CLB Văn học", personality:"Tinh tế, giàu tưởng tượng", speakingStyle:"Hơi thơ nhưng tự nhiên", reason:"Ngồi quan sát phố và viết bài", runningJoke:"Miêu tả sốt như phân tích tác phẩm", arc:"Dám gửi truyện ngắn đầu tiên đi dự thi", relations:["co-mai","han"], favoriteFood:"dau-hu", dislikedFood:null, preferredSauce:"sot-ngot", patienceMultiplier:1.08, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["short-story"], dialogue:{
      firstVisit:["Mùi đồ chiên làm khúc đường này tự nhiên có mở bài."], normal:["Cá viên vàng như nắng cuối giờ.","Sốt ngọt hôm nay có hậu vị vui.","Em đang tìm một cái kết, chắc ăn trước.","Quầy đông nghe như đoạn cao trào.","Mưa xuống, khói bếp nhìn hay ghê.","Chị đừng lo, em chờ được.","Món giòn làm câu văn cũng đỡ bí.","Em viết về một quầy nhỏ, không ghi tên đâu.","Có những chiều chỉ cần một xiên nóng.","Bạn em bảo em tả đồ ăn quá dài.","Phần này có bố cục rất ổn.","Sốt cay là dấu chấm than.","Mayo là dấu ba chấm.","Em chọn món theo tâm trạng nhân vật.","Hôm nay cho em một đoạn kết giòn."], highRelationship:["Truyện của em có quầy này ở chương đẹp nhất.","Chị là độc giả đầu tiên nha."], fastService:["Nhanh như một câu ngắn đúng chỗ."], slowService:["Chờ cũng là một phần của câu chuyện."], wrongOrder:["Có vẻ tình tiết vừa rẽ nhầm hướng."], rain:["Mưa làm khúc đường này giống trang sách cũ."], exams:["Đề nghị luận dài, giờ em cần món ngắn gọn."], graduation:["Em sẽ nhớ mùi khói bếp trong đoạn kết tuổi học trò."]
    }}),
    npc({ id:"duong", name:"Dương", avatar:"./assets/characters/duong.svg", ageRole:"Học sinh đội bóng rổ", personality:"Năng lượng, thẳng thắn, tốt bụng", speakingStyle:"Nhanh, khỏe, thân thiện", reason:"Ăn bù sau giờ tập", runningJoke:"Luôn nói mua cho cả đội nhưng ăn trước một phần", arc:"Học cân bằng tập luyện và thi cử", relations:["khanh","vu"], favoriteFood:"bo-vien", dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:.92, portionSizeWeight:"group", schedule:"sports", storyEvents:["final-match"], dialogue:{
      firstVisit:["Chị làm phần lớn nha, tụi em vừa tập xong."], normal:["Một phần cho đội, một phần em giữ hộ.","Tập xong đói muốn ăn luôn cái khay.","Cho nhiều sốt nha chị.","Hôm nay ném ba điểm ngon lắm.","Khánh nói phần này nhỏ, đừng nghe nó.","Tụi em thắng thì mai đặt gấp đôi.","Em chạy thêm vòng nên được thêm xiên.","Món nào nhiều năng lượng nhất chị?","Cho em combo phục hồi cơ bắp.","Đừng để Quý cầm khay, nó chạy rớt.","Đội em đang bình chọn sốt.","Trận sau chị qua cổ vũ nha.","Em ăn nhanh để còn dọn sân.","Bò viên này đạt phong độ cao.","Thêm khoai là chiến thuật hợp lý."], highRelationship:["Quầy mình là tài trợ tinh thần của đội.","Huy chương đầu tiên tụi em đem qua khoe chị."], fastService:["Tốc độ này vào đội chạy được đó chị."], slowService:["Không sao, em coi như nghỉ giữa hiệp."], wrongOrder:["Lệch chiến thuật rồi, làm lại nha chị."], rain:["Sân ướt nghỉ tập, vậy ăn thêm."], exams:["Thi xong em thấy chạy mười vòng còn dễ hơn."], graduation:["Sau này về sân cũ, em ghé quầy đầu tiên."]
    }}),
    npc({ id:"han", name:"Hân", avatar:"./assets/characters/han.svg", ageRole:"Học sinh lớp 12 trầm tính", personality:"Kín đáo, chăm chỉ, tử tế", speakingStyle:"Nhẹ, ngắn, lịch sự", reason:"Có chỗ nghỉ yên giữa lịch ôn dày", runningJoke:"Luôn nói không đói rồi gọi thêm", arc:"Tự tin chọn ngành và đi học xa", relations:["an","vu"], favoriteFood:"tom-vien", dislikedFood:"ho-lo", preferredSauce:"mayonnaise", patienceMultiplier:1.22, portionSizeWeight:"normal", schedule:"quiet", storyEvents:["major-choice","ielts-result"], dialogue:{
      firstVisit:["Cho em một phần nhỏ thôi ạ."], normal:["Em ngồi đây một chút được không?","Hôm nay em không đói lắm.","Dạ... thêm một xiên nữa.","Mayo giúp em bớt cay.","Em vừa học xong ca tối.","Ở đây ồn mà dễ chịu.","Chị chọn món giúp em cũng được.","Em đang chờ kết quả.","Cho em mang về một phần.","Bạn em sắp qua ạ.","Em cần nghỉ não năm phút.","Món hôm qua ngon lắm.","Dạ em chờ được.","Hôm nay em làm xong đề sớm.","Em nghĩ em biết mình muốn học gì rồi."], highRelationship:["Em chưa kể ai, nhưng chắc em sẽ chọn ngành em thích.","Nếu đi học xa, em sẽ nhớ quầy mình."], fastService:["Nhanh quá, cảm ơn chị."], slowService:["Không sao đâu ạ, em đang cần ngồi yên."], wrongOrder:["Dạ... hình như không phải món em gọi."], rain:["Cho em trú mưa một lát với ạ."], exams:["Em hơi lo, nhưng chắc làm được."], graduation:["Em vui mà cũng thấy trống trống."]
    }}),
    npc({ id:"vu", name:"Vũ", avatar:"./assets/characters/vu.svg", ageRole:"Thành viên CLB tranh biện", personality:"Lý luận, dí dỏm, hơi vụng khi ngại", speakingStyle:"Lập luận mọi lựa chọn", reason:"Tranh luận sốt nào ngon nhất", runningJoke:"Bảo vệ mayonnaise như một luận đề", arc:"Học nói điều mình thật sự nghĩ với Hân", relations:["han","duong"], favoriteFood:"pho-mai", dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.02, portionSizeWeight:"normal", schedule:"club", storyEvents:["debate-final","awkward-confession"], dialogue:{
      firstVisit:["Em có ba luận điểm chứng minh mayo hợp cá viên."], normal:["Tương ớt phổ biến không có nghĩa là tối ưu.","Em xin phản biện lựa chọn sốt mix.","Khẩu vị cá nhân vẫn cần bằng chứng.","Một phần phô mai củng cố lập trường của em.","Dương đang đánh tráo khái niệm đó.","Em không cãi, em đang làm rõ.","Cho em ví dụ thực nghiệm hôm nay.","Mayo có tính nhất quán cao.","Em đề nghị thử mù hai loại sốt.","Câu hỏi là ngon hơn, không phải cay hơn.","Hân tới chưa chị? Em hỏi để... biết thôi.","Em chuẩn bị bài nói, cần năng lượng.","Đơn này là kết luận tạm thời.","Em thừa nhận sốt ngọt cũng có điểm mạnh.","Hôm nay em không tranh luận. Chắc vậy."], highRelationship:["Chị đừng nói Hân là em hỏi nha.","Em đã quyết định nói thật, không cần ba luận điểm nữa."], fastService:["Bằng chứng thuyết phục."], slowService:["Em có thời gian chuẩn bị phản biện."], wrongOrder:["Dữ kiện này không hỗ trợ kết luận rồi chị."], rain:["Mưa không bác bỏ nhu cầu ăn vặt."], exams:["Em viết hết giờ nhưng vẫn thiếu kết luận."], graduation:["Lập luận nào cũng phải tới lúc chốt lại."]
    }}),
    npc({ id:"my", name:"My", avatar:"./assets/characters/my.svg", ageRole:"Học sinh săn ưu đãi", personality:"Nhanh mắt, thực tế, vui vẻ", speakingStyle:"Luôn để ý giá và khuyến mãi", reason:"Tìm món ngon lời nhất", runningJoke:"Nhớ giá cũ chính xác hơn chủ quầy", arc:"Dùng tài tính toán tổ chức gây quỹ lớp", relations:["tram","gia-huy"], favoriteFood:"khoai-tay", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.0, portionSizeWeight:"normal", schedule:"recess", storyEvents:["fundraiser"], dialogue:{
      firstVisit:["Mua hai phần có ưu đãi gì không chị? Em hỏi cho biết thôi."], normal:["Hôm qua cá viên mười hai nghìn đúng không?","Em đã so giá ba quầy rồi.","Ngon và hợp ví là tiêu chí kép.","Có thẻ khách quen chưa chị?","Em mua cho nhóm nên tính tròn nha.","Phần này tỷ lệ giá trên độ no tốt.","Khuyến mãi không? Không sao, em hỏi trước.","Khoai hôm nay nhiều hơn ba miếng.","Em nhớ giá giỏi chứ không khó tính.","Cho em món có lợi nhất cho ngân sách.","Quỹ lớp không chi đồ ăn, tiếc ghê.","Em có thể thiết kế bảng giá giúp chị.","Đừng ghi giá nhỏ quá, khách hỏi hoài.","Em quay lại vì ngon, không chỉ vì giá.","Nếu thêm combo học sinh thì hợp lý."], highRelationship:["Đợt gây quỹ nhờ quầy mình mà đủ mục tiêu đó chị.","Em thôi so giá rồi, quầy quen quan trọng hơn."], fastService:["Nhanh vậy là tiết kiệm cả thời gian."], slowService:["Chờ thêm thì phần có nhiều hơn không chị?"], wrongOrder:["Món này giá trị khác đơn em đặt nha."], rain:["Mưa mà có giảm giá trú mưa không chị? Em đùa thôi."], exams:["Điểm chưa biết, chi tiêu vẫn phải biết."], graduation:["Em giữ bảng giá cũ làm kỷ niệm nha."]
    }}),
    npc({ id:"gia-huy", name:"Gia Huy", avatar:"./assets/characters/gia-huy.svg", ageRole:"Học sinh lớp 10", personality:"Tò mò, hơi ngợp, dễ kết bạn", speakingStyle:"Lịch sự nhưng hỏi nhiều", reason:"Tìm một góc quen ở trường mới", runningJoke:"Luôn hỏi đây có phải hàng bí mật của khối trên", arc:"Từ tân binh bỡ ngỡ thành người dẫn bạn mới", relations:["my","tram"], favoriteFood:"ca-vien", dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.1, portionSizeWeight:"normal", schedule:"early", storyEvents:["first-week"], dialogue:{
      firstVisit:["Chị ơi, quầy này có phải chỗ mấy anh chị khối trên hay nói không?"], normal:["Em mới biết đường ra cổng này.","Món nào dễ ăn nhất vậy chị?","Trường đông hơn em tưởng.","Bạn cùng bàn chỉ em qua đây.","Em chưa nhớ hết phòng học nữa.","Cho em giống bạn trước cũng được.","Cá viên là lựa chọn an toàn ha chị.","Em tham gia câu lạc bộ nào thì vui?","Hôm nay em không đi lạc.","Chị nhớ tên em rồi hả?","Em dẫn thêm bạn mới qua nha.","Quầy này dễ tìm hơn phòng thí nghiệm.","Em bắt đầu quen trường rồi.","Khối trên nhìn vậy mà thân thiện.","Cho em phần tự tin trước tiết mới."], highRelationship:["Giờ em chỉ đường quầy cho mấy bạn mới rồi đó.","Năm sau em cũng thành khách lâu năm ha chị."], fastService:["Nhanh ghê, em còn kịp tìm lớp."], slowService:["Dạ em chờ được, em đang coi bản đồ trường."], wrongOrder:["Em mới nên không chắc... nhưng hình như sai ạ."], rain:["Em quên đem áo mưa từ tuần đầu luôn."], exams:["Bài kiểm tra đầu tiên làm em hết hồn."], graduation:["Em mới vào mà các anh chị đã sắp đi rồi."]
    }}),
    npc({ id:"thay-minh", name:"Thầy Minh", avatar:"./assets/characters/thay-minh.svg", ageRole:"Hiệu trưởng hư cấu", personality:"Điềm tĩnh, chuẩn mực, hài hước kín đáo", speakingStyle:"Chậm, trang trọng rồi bất ngờ đời thường", reason:"Ban đầu kiểm tra an toàn, sau thành khách kín tiếng", runningJoke:"Khẳng định chỉ tới quan sát rồi vẫn gọi món", arc:"Từ dè dặt thành người ủng hộ không gian gặp gỡ sau giờ học", relations:["co-lan","chi-hong"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-ngot", patienceMultiplier:1.35, portionSizeWeight:"normal", schedule:"dismissal", storyEvents:["safety-inspection"], dialogue:{
      firstVisit:["Thầy đang quan sát vấn đề an toàn thực phẩm."], normal:["Thầy chỉ đi ngang qua.","...cho thầy một phần.","Các em cứ nói chuyện tự nhiên.","Sao tất cả im vậy?","Thầy không kiểm tra bài ở đây.","Hôm nay quầy trật tự nhỉ.","Cho thầy món bất kỳ, vừa phải.","Thầy đánh giá cao khu vực sạch sẽ.","Không cần báo với văn phòng thầy ghé.","Tan học rồi, các em thư giãn đi.","Sốt ngọt một chút thôi.","Thầy đang khảo sát thói quen học sinh.","Khảo sát này cần thử món.","Không, đây không phải cuộc họp.","Quầy nhỏ mà kết nối được nhiều người."], highRelationship:["Thầy thật ra thích nhìn các em cười nói sau giờ học.","Cứ giữ quầy sạch và tử tế như vậy nhé."], fastService:["Hiệu suất tốt."], slowService:["Thầy có thể đợi, hôm nay không họp."], wrongOrder:["Có lẽ đơn của thầy và bạn nào đó bị đổi."], rain:["Mưa lớn, cho các em trú gọn vào nhé."], exams:["Thầy không hỏi điểm. Hôm nay thôi."], graduation:["Những nơi nhỏ như thế này thường ở lại lâu nhất trong ký ức."]
    }}),
    npc({ id:"co-lan", name:"Cô Lan", avatar:"./assets/characters/co-lan.svg", ageRole:"Phó hiệu trưởng hư cấu", personality:"Chính xác, nhanh, quan tâm kín đáo", speakingStyle:"Con số rõ ràng, câu ngắn", reason:"Đặt phần cho giáo viên làm muộn", runningJoke:"Biết chính xác mọi việc mất bao nhiêu phút", arc:"Từ kiểm tra bảng giá thành khách đặt nhóm quen thuộc", relations:["thay-minh","tram"], favoriteFood:null, dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.05, portionSizeWeight:"group", schedule:"late", storyEvents:["teacher-group-order"], dialogue:{
      firstVisit:["Cho cô ba phần. Cô quay lại sau bảy phút."], normal:["Bảy phút rồi.","Ba phần, hai cay, một không cay.","Cô đã ghi số lượng.","Dòng giá này căn chưa đều.","Hôm nay đông hơn mười hai người.","Cô có cuộc họp sau tám phút.","Cho giáo viên trực tối nhé.","Mỗi phần ghi riêng giúp cô.","Cô nhớ lần trước là sốt ngọt.","Không cần vội quá, cần chính xác.","Biển quầy mới dễ đọc hơn.","Cô đi ngang, tiện đặt luôn.","Thời gian chiên trung bình là bao lâu?","Bốn phút rưỡi. Cô canh được.","Hôm nay quy trình gọn hơn."], highRelationship:["Quầy em làm việc rất có hệ thống.","Đợt sự kiện trường cô nhờ quầy hỗ trợ nhé."], fastService:["Sớm hơn dự kiến ba mươi giây."], slowService:["Chậm một phút mười hai giây."], wrongOrder:["Đối chiếu lại: ba phần, hai cay, một thường."], rain:["Mưa sẽ kéo dài khoảng hai mươi phút."], exams:["Phòng giáo viên hôm nay cần nhiều đồ ăn."], graduation:["Lịch trình lễ đã chặt, riêng cảm xúc thì khó tính phút."]
    }}),
    npc({ id:"thay-phong", name:"Thầy Phong", avatar:"./assets/characters/thay-phong.svg", ageRole:"Giáo viên Toán hư cấu", personality:"Logic, tỉnh, hài khô", speakingStyle:"Đo lường và hỏi xác suất", reason:"Tính tỷ lệ giá trên độ ngon", runningJoke:"Đòi con số chính xác cho nhận xét đời thường", arc:"Chấp nhận có vài thứ không cần tối ưu tuyệt đối", relations:["co-mai","thay-khoi"], favoriteFood:null, dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.25, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["teacher-debate"], dialogue:{
      firstVisit:["Xác suất phần của thầy bị cháy là bao nhiêu?"], normal:["Thấp là bao nhiêu phần trăm?","Tăng giá hai nghìn, tăng lượng mười phần trăm: hợp lý.","Sốt này phân bố chưa đều.","Thầy cần một mẫu đủ lớn để kết luận.","Cho thầy thử lại món khác.","Ba viên không tạo thành cấp số cộng.","Đừng gọi đó là ngẫu nhiên nếu em tự chọn.","Giá trị kỳ vọng của phần này khá cao.","Tan học không có nghĩa là ngừng tính.","Thầy chỉ tính để dễ quyết định.","Mayo giảm độ cay một cách đo được.","Hàng chờ hôm nay tăng tuyến tính.","Nếu gọi hai phần, thời gian có gấp đôi không?","Kết quả thực nghiệm: ngon.","Sai số hôm nay chấp nhận được."], highRelationship:["Có vài thứ ngon là đủ, không cần chứng minh.","Thầy đã bỏ bảng tính đánh giá quầy rồi."], fastService:["Nhanh hơn trung bình mười tám phần trăm."], slowService:["Quan sát thêm cũng tăng độ tin cậy."], wrongOrder:["Kết quả khác giả thiết ban đầu."], rain:["Xác suất học sinh quên áo mưa khá cao."], exams:["Điểm số là dữ liệu, không phải toàn bộ con người."], graduation:["Một chặng kết thúc, dãy tiếp theo bắt đầu."]
    }}),
    npc({ id:"co-mai", name:"Cô Mai", avatar:"./assets/characters/co-mai.svg", ageRole:"Giáo viên Văn hư cấu", personality:"Quan sát, biểu cảm, ấm áp", speakingStyle:"Giàu hình ảnh nhưng không dài", reason:"Thích không khí đời thường quanh quầy", runningJoke:"Biến nước sốt thành ẩn dụ", arc:"Giúp An tin vào bài viết của mình", relations:["an","thay-phong"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-ngot", patienceMultiplier:1.3, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["writing-contest"], dialogue:{
      firstVisit:["Cá viên hôm nay vàng đều như một buổi chiều tháng ba."], normal:["Sốt cay là điểm nhấn có phần quyết liệt.","Mùi thơm kéo người ta chậm lại.","Một quầy nhỏ cũng có câu chuyện riêng.","Hôm nay nắng mềm hơn hôm qua.","Cho cô phần có màu đẹp nhất.","Các em chỉ đang ăn thôi, cô biết.","Sốt ngọt làm đoạn kết dịu lại.","Khói bếp che mất nửa con đường.","An vừa gửi cô bài viết.","Món ăn nhớ bằng mùi lâu hơn bằng tên.","Cô sẽ không phân tích xiên này.","...nhưng bố cục màu rất tốt.","Cho cô thêm phần mang về.","Tiếng cười ở đây nghe rất thật.","Chiều cuối tuần nên có món nóng."], highRelationship:["Cô nghĩ quầy em đã thành một phần ký ức của các bạn.","Bài của An có nhắc nơi này, rất đẹp."], fastService:["Gọn như một câu kết tốt."], slowService:["Chờ làm mùi thơm rõ hơn."], wrongOrder:["Hình như nhân vật đã nhận nhầm đạo cụ."], rain:["Mưa biến mái bạt thành nhạc nền."], exams:["Đừng để một bài viết quyết định hết tâm trạng."], graduation:["Có những buổi chiều sau này chỉ còn trong hồi ức."]
    }}),
    npc({ id:"co-thao", name:"Cô Thảo", avatar:"./assets/characters/co-thao.svg", ageRole:"Giáo viên Anh hư cấu", personality:"Vui, nhanh, khích lệ", speakingStyle:"Tiếng Việt xen vài cụm tiếng Anh ngắn", reason:"Ăn nhẹ sau giờ dạy và hỏi thăm học sinh", runningJoke:"Câu How was your test? làm cả nhóm im lặng", arc:"Giúp Hân bớt sợ kết quả IELTS", relations:["han","co-lan"], favoriteFood:null, dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.15, portionSizeWeight:"normal", schedule:"dismissal", storyEvents:["ielts-talk"], dialogue:{
      firstVisit:["Cho cô một phần. Spicy but not too spicy nha."], normal:["How was your test? Sao im hết vậy?","Một phần quick and simple nhé.","Hôm nay các em làm bài ổn không?","No pressure, cô chỉ hỏi thôi.","Sốt ít cay thôi nha.","Good smell! Cô đứng xa vẫn thấy.","Cho cô thêm phần take away.","Hân hôm nay tự tin hơn rồi.","Món này exactly what I need.","Các em ăn rồi nhớ vào lớp.","Cô không kiểm tra từ vựng ở đây đâu.","Well done, quầy đông mà vẫn nhanh.","Một phần cho cô, một phần cho đồng nghiệp.","Keep going nha, gần hết tuần rồi.","Hôm nay cho cô thử món mới."], highRelationship:["Quầy em có atmosphere rất dễ thương.","Hân báo điểm rồi, cô ấy làm tốt lắm."], fastService:["Excellent timing!"], slowService:["It's okay, cô chưa vội."], wrongOrder:["Hmm, this is not what I ordered. Nhưng mình làm lại nha."], rain:["Rainy day, hot snacks. Perfect."], exams:["One test doesn't define you."], graduation:["Goodbye không có nghĩa là không gặp lại."]
    }}),
    npc({ id:"thay-khoi", name:"Thầy Khôi", avatar:"./assets/characters/thay-khoi.svg", ageRole:"Giáo viên Hóa hư cấu", personality:"Tò mò, thực tế, thích quan sát", speakingStyle:"Giải thích phản ứng rất ngắn", reason:"Quan sát độ nóng dầu rồi mua luôn", runningJoke:"Xem chảo như phòng thí nghiệm", arc:"Giúp quầy cải thiện quy trình chiên", relations:["thay-phong","thay-tung"], favoriteFood:null, dislikedFood:null, preferredSauce:"tuong-ca", patienceMultiplier:1.2, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["oil-test"], dialogue:{
      firstVisit:["Dầu hôm nay nóng hơn hôm qua đúng không?"], normal:["Nhìn màu là biết.","Phản ứng nâu hóa đang đẹp.","Đừng lo, thầy không giảng dài.","Cho thầy mẫu... à, một phần.","Nhiệt ổn định thì món đều.","Chảo này giữ nhiệt khá tốt.","Sốt chua làm vị cân bằng.","Mùi thơm là dữ kiện rõ nhất.","Thầy chỉ quan sát thôi.","Quan sát xong thì ăn.","Xúc xích cần thêm vài giây.","Dầu sạch, màu sáng.","Phần này phản ứng thành công.","Không cần ống nghiệm đâu.","Mai thầy mang nhiệt kế. Thầy đùa."], highRelationship:["Quy trình quầy em giờ rất ổn định.","Thầy ghi công thức sốt nhưng không công bố đâu."], fastService:["Tốc độ phản ứng tốt."], slowService:["Nhiệt thấp thì cần thời gian, hợp lý."], wrongOrder:["Có vẻ mẫu bị gắn nhãn sai."], rain:["Độ ẩm cao, đồ nóng càng hấp dẫn."], exams:["Nhớ cân bằng phương trình và cân bằng nghỉ ngơi."], graduation:["Phản ứng kết thúc nhưng sản phẩm còn lại."]
    }}),
    npc({ id:"thay-tung", name:"Thầy Tùng", avatar:"./assets/characters/thay-tung.svg", ageRole:"Giáo viên Tin hư cấu", personality:"Ít lời, tinh ý, hài nhẹ", speakingStyle:"Ngắn, đúng trọng tâm", reason:"Ăn sau giờ coi phòng máy", runningJoke:"Mọi lỗi code đều xử lý sau khi ăn", arc:"Âm thầm hỗ trợ đội tuyển của Nhân", relations:["nhan","thay-khoi"], favoriteFood:null, dislikedFood:null, preferredSauce:"mayonnaise", patienceMultiplier:1.3, portionSizeWeight:"normal", schedule:"late", storyEvents:["lab-night"], dialogue:{
      firstVisit:["Một phần. Ít sốt."], normal:["Ăn xong sửa.","Code lỗi à? Ăn xong.","Máy chạy, người cũng cần nạp.","Hôm nay phòng máy yên.","Nhân chưa về à?","Cho thầy món nhanh nhất.","Không cần tối ưu mọi thứ.","Quầy này ít bug.","Mayo. Không tranh luận.","Một phần mang lên phòng máy.","Thầy đang chờ cập nhật.","Đơn cũ, dữ liệu mới.","Ổn. Không có log lỗi.","Hôm nay thầy nói nhiều rồi.","Thêm một phần."], highRelationship:["Đội tuyển làm tốt. Nhân cũng biết nghỉ hơn rồi.","Nếu cần bảng tính bán hàng, nói thầy."], fastService:["Nhanh. Pass."], slowService:["Không timeout."], wrongOrder:["Sai config rồi."], rain:["Mạng chậm, quầy vẫn chạy."], exams:["Lưu bài thường xuyên."], graduation:["Nhớ backup kỷ niệm."]
    }}),
    npc({ id:"co-huong", name:"Cô Hương", avatar:"./assets/characters/co-huong.svg", ageRole:"Phụ huynh chờ đón con hư cấu", personality:"Cởi mở, hay chuyện, tốt bụng", speakingStyle:"Thân tình, tự nhiên", reason:"Đứng chờ con rồi dần quen cả quầy", runningJoke:"Nói chỉ đứng chờ rồi mua hai phần", arc:"Từ người đứng ngoài thành cầu nối phụ huynh–học sinh", relations:["chu-thanh","co-thao"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-ngot", patienceMultiplier:1.35, portionSizeWeight:"group", schedule:"dismissal", storyEvents:["waiting-mom"], dialogue:{
      firstVisit:["Cô chỉ đứng chờ con thôi."], normal:["Thôi cho cô một phần.","Cho thêm phần mang về nữa.","Con cô thấy cô quen hết ở đây là nó ngại.","Hôm nay tan trễ hả con?","Cô đứng đây riết biết lịch luôn.","Mấy đứa nhỏ học căng quá.","Cho cô phần ít cay.","Cô mua hộ bạn phụ huynh kia.","Mưa rồi, tụi nhỏ chưa ra.","Quầy em đông vui ghê.","Cô nghe chuyện mà không kể đâu.","Con cô bảo cô nói chuyện nhiều.","Đứng chờ không cũng buồn miệng.","Hôm nay cô mua đúng một phần. Chắc vậy.","Thêm phần cuối thôi nha."], highRelationship:["Cô coi quầy như điểm hẹn luôn rồi.","Mai con cô tự về, chắc cô vẫn ghé."], fastService:["Nhanh vậy cô chưa kịp kể hết chuyện."], slowService:["Cô chờ con nên chờ món luôn được."], wrongOrder:["Không sao, phần này chắc con cô cũng ăn."], rain:["Mấy đứa vô né mưa đi con."], exams:["Cô không hỏi điểm, cô chỉ hỏi ăn chưa."], graduation:["Con lớn rồi, cô lại nhớ những ngày đứng chờ."]
    }}),
    npc({ id:"chu-thanh", name:"Chú Thành", avatar:"./assets/characters/chu-thanh.svg", ageRole:"Phụ huynh nghiêm nghị hư cấu", personality:"Kỷ luật ngoài mặt, mềm lòng bên trong", speakingStyle:"Nghiêm rồi tự mâu thuẫn", reason:"Đón con và bí mật ăn vặt", runningJoke:"Món thứ hai luôn nói mua cho con", arc:"Học cách bớt áp lực chuyện điểm số với con", relations:["co-huong","thay-minh"], favoriteFood:null, dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.18, portionSizeWeight:"normal", schedule:"dismissal", storyEvents:["strict-dad"], dialogue:{
      firstVisit:["Mấy món chiên ăn nhiều không tốt."], normal:["...cho chú hai phần.","Phần thứ hai cho con chú.","Nó chưa ra nhưng cứ làm trước.","Học phải có giờ, ăn cũng vậy.","Cho ít dầu nhé.","Chú chỉ thử chất lượng.","Đừng nói với con chú chú ghé trước.","Hôm nay nó thi, cho phần nó thích.","Điểm quan trọng nhưng sức khỏe cũng quan trọng.","Chú đứng đây đúng năm phút.","Sốt cay riêng giúp chú.","Nó bảo chú khó. Chắc cũng đúng.","Cho chú mang về thêm một phần.","Đây là ngoại lệ trong tuần.","Ngoại lệ thứ hai."], highRelationship:["Chú đang tập hỏi con có mệt không trước khi hỏi điểm.","Hai cha con giờ cùng ghé, đỡ phải giấu."], fastService:["Tác phong tốt."], slowService:["Chú chờ được, miễn làm kỹ."], wrongOrder:["Chú đặt khác, kiểm tra lại nhé."], rain:["Chú mang dư áo mưa cho tụi nhỏ."], exams:["Nó cố gắng rồi, kết quả tính sau."], graduation:["Tự nhiên thấy nó lớn nhanh quá."]
    }}),
    npc({ id:"chu-sau", name:"Chú Sáu", avatar:"./assets/characters/chu-sau.svg", ageRole:"Bảo vệ trường hư cấu", personality:"Điềm đạm, biết mọi lịch trình", speakingStyle:"Miền Nam thân mật, chắc nịch", reason:"Ghé đầu và cuối ca, báo tin quanh trường", runningJoke:"Đoán đúng ai sắp chạy trễ", arc:"Trở thành người kể chuyện thầm lặng của khu phố", relations:["quy","thay-minh"], favoriteFood:null, dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.5, portionSizeWeight:"normal", schedule:"any", storyEvents:["weather-warning"], dialogue:{
      firstVisit:["Bán ở đây hả con? Giữ sạch là được nghen."], normal:["Chút nữa thằng Quý chạy tới cho coi.","Thấy chưa, chú nói có sai đâu.","Hôm nay tan học sớm đó con.","Chiều coi bộ mưa à nghen.","Cho chú phần nóng nóng.","Tụi nhỏ bữa nay thi nên mặt căng.","Sắp có sự kiện, chuẩn bị thêm đồ đi.","Khúc này đông mà vui.","Chú trực thêm một lát.","Thầy Minh đi ngang hồi nãy đó.","Con bán càng ngày càng vững tay.","Để chú coi xe giúp cho.","Quý mà tới sớm chắc trời mưa.","Chị Hồng bên kia hỏi thăm đó.","Cuối ngày còn phần nào làm chú phần đó."], highRelationship:["Quầy con thành cái mốc của cả khúc đường rồi.","Có gì cần cứ gọi chú một tiếng."], fastService:["Nhanh gọn dữ hen."], slowService:["Từ từ, chú chưa hết ca."], wrongOrder:["Ủa hình như phần này của đứa nhỏ nào rồi."], rain:["Chú nói mưa là mưa mà."], exams:["Tụi nhỏ cố dữ, cho tụi nó ăn no nghen."], graduation:["Mỗi năm một lứa đi, cái cổng vẫn đứng đây."]
    }}),
    npc({ id:"chi-hong", name:"Chị Hồng", avatar:"./assets/characters/chi-hong.svg", ageRole:"Chủ quầy bánh tráng bên cạnh", personality:"Cạnh tranh, lanh lẹ, tốt bụng", speakingStyle:"Tự tin, cà khịa nhẹ nhưng chân thành", reason:"Nghiên cứu đối thủ rồi thành bạn", runningJoke:"Ăn liên tục nhưng gọi là nghiên cứu thị trường", arc:"Nghi ngờ → cạnh tranh → hợp tác → đối thủ thân thiện", relations:["thay-minh","chu-sau"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-mix", patienceMultiplier:1.28, portionSizeWeight:"normal", schedule:"late", storyEvents:["rival-intro","food-street-rush","supply-help"], dialogue:{
      firstVisit:["Mới bán hả? Khúc này khách khó lắm đó... cho chị phần cá viên coi thử."], normal:["Chị đang nghiên cứu thị trường.","Ba ngày liên tục vì thị trường phức tạp.","Cho chị một phần, đừng tưởng chị công nhận ngon.","...cũng được.","Hôm nay bên chị đông hơn chút xíu thôi.","Biển mới đẹp đó, chưa bằng bên chị.","Khách hỏi đồ chiên chị chỉ qua đây đó.","Cho chị thử món bán chạy nhất.","Đừng nhìn, chị mua cho khách.","Làm chị hai phần. Cho chị.","Bên chị hết tương ớt, cho mượn chai.","Mai đừng tưởng chị nhường khách nha.","Khói bên em bay qua thơm quá.","Cạnh tranh lành mạnh phải nếm thường xuyên.","Bánh tráng bên chị cũng ngon, nhớ qua đó."], highRelationship:["Có đợt đông quá thì hai bên chia khách.","Em bán được là chị mừng, nhưng mai vẫn cạnh tranh nha."], fastService:["Tốc độ khá đó. Chị ghi nhận thôi."], slowService:["Nghiên cứu kỹ thì phải chờ."], wrongOrder:["Đơn đối thủ mà cũng làm sai hả? Làm lại coi."], rain:["Kéo bạt sát qua, hai quầy trú chung."], exams:["Bữa nay tụi nhỏ căng, hai bên bớt chọc nhau."], graduation:["Tụi nhỏ đi hết thấy khúc đường vắng ghê."]
    }}),
    npc({ id:"bac-tu", name:"Bác Tư", avatar:"./assets/characters/bac-tu.svg", ageRole:"Bác tài xe ôm công nghệ", personality:"Thoải mái, quan sát phố xá", speakingStyle:"Chậm rãi, chuyện đời thường", reason:"Nghỉ giữa các cuốc xe", runningJoke:"Cuốc cuối luôn kéo dài thêm một phần", arc:"Giúp giao đơn khi quầy đông", relations:["chu-sau","chi-hong"], favoriteFood:null, dislikedFood:null, preferredSauce:"tuong-ot", patienceMultiplier:1.45, portionSizeWeight:"normal", schedule:"any", storyEvents:["delivery-help"], dialogue:{
      firstVisit:["Cho bác phần ăn lót dạ giữa hai cuốc."], normal:["Cuốc cuối rồi bác nghỉ.","Ăn xong mới nhận cuốc cuối thật.","Đường chiều nay đông dữ.","Cho bác món nào nóng.","Bác ngồi mé này không vướng khách.","Tụi nhỏ tan là xe kín đường.","Bác chạy khắp Biên Hòa, mùi quầy này dễ nhận.","Một phần mang đi nghen.","Mưa là đơn giao tăng.","Khách chờ được, bụng bác không.","Bên kia đường kẹt xe đó.","Chú Sáu đoán mưa giỏi thiệt.","Cho ít cay, còn chạy xe.","Quầy đông bác phụ giao cũng được.","Xong phần này bác đi. Thiệt."], highRelationship:["Có đơn gần đây cứ gọi bác chở giúp.","Quầy con làm khúc đường vui hơn."], fastService:["Nhanh, bác kịp nhận cuốc."], slowService:["Không sao, bác tắt ứng dụng rồi."], wrongOrder:["Chắc phần này giao nhầm tài xế rồi."], rain:["Mưa thì cứ bình tĩnh, đường trơn."], exams:["Chở mấy đứa đi thi ai cũng im re."], graduation:["Bác chở nhiều đứa từ ngày đầu tới ngày tốt nghiệp."]
    }}),
    npc({ id:"trang", name:"Trang", avatar:"./assets/characters/trang.svg", ageRole:"Học sinh, bạn thân của Quý và Trân", personality:"Nhanh nhẹn, thẳng thắn, thương bạn", speakingStyle:"Tự nhiên, hay kể chuyện nhóm bạn", reason:"Ghé quầy để ăn và dò xem hai bạn thân đã tới chưa", runningJoke:"Group chat có đủ ba người nhưng chẳng ai đọc đúng lúc", arc:"Học cách bớt lo thay cho cả nhóm", relations:["quy","tran"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:1.04, portionSizeWeight:"normal", schedule:"recess", storyEvents:["best-friends"], dialogue:{
      firstVisit:["Chị ơi, Quý với Trân có ghé chưa?"], normal:["Trân tới chưa chị?","Quý mà nói còn một phút là còn ba mươi giây đó.","Ba đứa em có group, nhưng không ai đọc.","Hôm nay em mua cho mình thôi.","Chị đừng tin Trân nếu nó nói chưa ăn.","Quý chạy ngang đây chưa chị?","Em vừa cứu cả nhóm khỏi quên bài tập.","Cho em món nào ăn xong đỡ cáu.","Tụi em thân nhau nên mới cãi nhiều vậy.","Trân bảo em giữ bí mật, em đang cố.","Em nhắn group rồi, chắc mai họ mới đọc.","Hôm nay cả ba đứa đều tới đúng giờ. Gần đúng.","Cho em mang thêm một phần cho Trân.","Quý nợ em một lần trực nhật.","Chị Thảo nhớ mặt tụi em nhanh thiệt."], highRelationship:["Quầy chị thành điểm hẹn chính thức của ba đứa em rồi."], fastService:["Nhanh hơn tốc độ Quý trả lời tin nhắn."], slowService:["Không sao, em chờ hai đứa kia luôn."], wrongOrder:["Hình như phần này của Trân rồi chị."], rain:["Ba đứa em lại quên chung một cây dù."], exams:["Tụi em chia nhau ôn, rồi chia nhau hoảng."], graduation:["Sau này group vẫn còn, quầy mình cũng phải còn nha chị."]
    }}),
    npc({ id:"tran", name:"Trân", avatar:"./assets/characters/tran.svg", ageRole:"Học sinh, bạn thân của Quý và Trang", personality:"Lém lỉnh, tình cảm, hay bày trò", speakingStyle:"Nhỏ giọng khi kể bí mật rồi tự nói quá to", reason:"Ăn trước nhưng thường dặn Thảo đừng kể với bạn", runningJoke:"Bí mật của Trân tồn tại khoảng ba phút", arc:"Biết tin bạn bè và nói thẳng điều mình cần", relations:["quy","trang"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:1.06, portionSizeWeight:"normal", schedule:"recess", storyEvents:["best-friends"], dialogue:{
      firstVisit:["Lát Trang hỏi thì chị đừng nói em ăn trước nha."], normal:["Em ghé một mình, chuyện này đừng lên group.","Trang có tới chưa chị?","Quý mà chạy qua thì giữ giùm em cái khăn.","Em không giấu gì hết. Chắc vậy.","Cho em phần nhỏ thôi, rồi thêm một phần nữa.","Ba đứa em cãi xong là đi ăn.","Chị Thảo biết nhiều bí mật quá rồi đó.","Em kể chị nghe nhưng chị không được cười.","Trang nói em bốc đồng. Em đang cân nhắc phản đối.","Quý lại quên hẹn, quen rồi chị.","Group tụi em đang có 127 tin chưa đọc.","Hôm nay em sẽ không ăn trước hai đứa kia.","...chị làm nhanh giúp em.","Em mua mang về để có bằng chứng là có nghĩ tới bạn.","Bạn thân là người vẫn chia đồ ăn sau khi cãi."], highRelationship:["Chị là thành viên danh dự của group rồi, nhưng không cần vào group đâu."], fastService:["Tốt, chưa ai kịp bắt gặp."], slowService:["Chắc giờ Trang biết em ở đây rồi."], wrongOrder:["Sai món rồi, nhưng đừng lấy lý do đó kể Trang nha."], rain:["Trang giữ dù, Quý giữ áo mưa, em giữ đồ ăn."], exams:["Ba đứa học chung được mười phút, nói chuyện hai tiếng."], graduation:["Tụi em hứa không để group im sau tốt nghiệp."]
    }}),
    npc({ id:"thuy", name:"Thủy", avatar:"./assets/characters/thuy.svg", ageRole:"Học sinh năng nổ của CLB truyền thông", personality:"Hoạt bát, tốt bụng, rất mê chị Thảo", speakingStyle:"Nhiệt tình, dễ lúng túng khi bị Thảo trêu", reason:"Vừa thích đồ chiên, vừa tìm mọi lý do hợp lý để ghé chị Thảo", runningJoke:"Nói nhớ cá viên nhưng ai cũng biết em nhớ chị Thảo", arc:"Giúp quảng bá quầy và học cách tự tin với cảm xúc của mình", relations:["trang","tran"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:1.2, portionSizeWeight:"normal", schedule:"club", storyEvents:["stall-promotion","obvious-crush"], dialogue:{
      firstVisit:["Chị Thảo hôm nay đẹp quá."], normal:["Chị Thảo ăn tối chưa?","Hôm qua chị cũng đẹp. Hôm nay cũng vậy.","Em ghé vì nhớ... nhớ cá viên.","Chị có mệt không? Em phụ dọn bảng nha.","Em làm poster giới thiệu quầy cho chị rồi.","Tóc chị hôm nay khác một chút đúng không?","Em mới tới hồi trưa, nhưng em đói nhanh.","Bạn em hỏi sao em thuộc giờ quầy mở.","Em mang thêm mấy bạn CLB qua nha chị.","Chị đứng bếp nóng lắm không?","Hôm nay em tổ chức sự kiện khá suôn sẻ.","Em vừa thuyết trình xong nên tự thưởng.","Quầy chị lên bài CLB được nhiều tim lắm.","Em tới ăn thôi nha. Thiệt.","Mai chị có bán không?"], highRelationship:["Em tới ăn hay tới gặp chị hả? ...cả hai."], fastService:["Chị làm gì cũng nhanh hết á."], slowService:["Không sao, em ngồi đây với chị được mà."], wrongOrder:["Không sao đâu chị, chị đừng buồn nha."], rain:["Chị có lạnh không? Em có áo khoác nè."], exams:["Thi xong em ghé đầu tiên đó."], graduation:["Em vẫn sẽ quay lại, không cần viện cớ CLB nữa."]
    }}),
    npc({ id:"hoc", name:"Học", avatar:"./assets/characters/hoc.svg", ageRole:"Học sinh hay trì hoãn", personality:"Tinh nghịch, thông minh, sát deadline", speakingStyle:"Biện minh rất trôi chảy cho việc chưa học", reason:"Nạp năng lượng trước khi bắt đầu học — theo lời em ấy", runningJoke:"Tên là Học nhưng câu trả lời thường là chưa", arc:"Bất ngờ nghiêm túc trong tuần thi và tự hoàn thành mục tiêu", relations:["quy","khanh"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:.98, portionSizeWeight:"normal", schedule:"late", storyEvents:["exam-focus"], dialogue:{
      firstVisit:["Em đang nạp năng lượng để học."], normal:["Học chưa hả chị? Chưa.","Em ăn xong là học thiệt.","Đây là giờ nghỉ trước khi bắt đầu.","Em đang nghiên cứu chiến lược ôn bài.","Sách ở trong cặp là bước đầu rồi.","Quý rủ em, em vô tội.","Cho em phần tạo động lực.","Em chưa trì hoãn, em đang chuẩn bị.","Tối nay em học ba chương. Kế hoạch là vậy.","Điện thoại em tự mở, không phải em.","Em đặt báo thức rồi tắt rất đúng giờ.","Hôm nay em có tiến bộ: mở sách.","Ăn xong em không đi đâu nữa.","Khánh nói ăn giúp nhớ lâu.","Chị đừng hỏi bài, hỏi món thôi."], highRelationship:["Chị thấy chưa, tuần này em học thật rồi."], fastService:["Nhanh vậy em hết lý do trì hoãn rồi."], slowService:["Tốt, em có thêm thời gian chưa học."], wrongOrder:["Sai bài... à sai món rồi chị."], rain:["Mưa là lý do khách quan để chưa về học."], exams:["Hôm nay em học thật. Đừng ai làm ồn."], graduation:["Sau này chắc em vẫn nói mai học, nhưng em sẽ làm được."]
    }}),
    npc({ id:"tho", name:"Thơ", avatar:"./assets/characters/tho.svg", ageRole:"Cán bộ an toàn thực phẩm hư cấu", personality:"Chuyên nghiệp, điềm tĩnh, quan sát kỹ", speakingStyle:"Lịch sự, ngắn gọn, vô tình làm Thảo hồi hộp", reason:"Kiểm tra an toàn khu bán hàng rồi trở thành khách quen", runningJoke:"Mỗi lần tới ăn, Thảo vẫn tưởng sắp bị kiểm tra", arc:"Từ người kiểm tra đáng ngại thành người hướng dẫn thân thiện", relations:["chu-sau","chi-hong"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:1.35, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["food-safety-intro","oil-hint"], dialogue:{
      firstVisit:["Chào em. Chị kiểm tra một chút."], normal:["Cho chị một phần.","Hôm nay chị tới ăn.","Khu chế biến sạch đó.","Nhớ thay dầu đúng lúc nha em.","Rác gọn rồi, tốt.","Đồ sống và đồ chín để riêng nhé.","Em đừng căng thẳng, chị chưa hỏi gì mà.","Chị đi ngang nên ghé thôi.","Mùi thơm nên chị đổi lịch ăn trưa.","Cho ít cay giúp chị.","Quầy đông vẫn phải giữ gọn nha.","Hôm nay không kiểm tra.","Em muốn chị kiểm tra không?","Chị nói đùa thôi.","Làm chị phần ngẫu nhiên nhất."], highRelationship:["Giờ chị tới là em bớt run rồi ha."], fastService:["Nhanh mà vẫn gọn. Tốt."], slowService:["Làm đúng trước, nhanh sau."], wrongOrder:["Đơn này chưa đúng, mình kiểm tra lại nhé."], rain:["Mưa thì che nguyên liệu kỹ hơn nha."], exams:["Tụi nhỏ thi, em cũng đừng quên nghỉ."], graduation:["Quầy giữ chuẩn từ ngày đầu tới giờ, đáng khen."]
    }}),
    npc({ id:"co-linh", name:"Cô Linh", avatar:"./assets/characters/co-linh.svg", ageRole:"Giáo viên tiếng Anh hư cấu", personality:"Vui vẻ, gần gũi, tinh tế", speakingStyle:"Thỉnh thoảng chèn một cụm tiếng Anh ngắn tự nhiên", reason:"Ăn nhẹ sau giờ dạy", runningJoke:"Spicy, nhưng luôn thêm not too spicy", arc:"Giúp học sinh bớt sợ nói sai", relations:["co-mai","thay-minh"], favoriteFood:null, dislikedFood:null, preferredSauce:null, patienceMultiplier:1.25, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:["english-club"], dialogue:{
      firstVisit:["Cho cô một phần. Spicy but not too spicy nha."], normal:["One portion, please.","Hôm nay cô nói tiếng Việt thôi. Maybe.","Cho cô món nào crispy nhất.","Not too spicy nha em.","Học sinh vừa thuyết trình tốt lắm.","Sai một từ không sao, miễn dám nói.","Quầy đông ghê. Very popular.","Cho cô mang về một phần.","Cô đang chấm bài, cần năng lượng.","Mayo hôm nay nghe hợp lý.","Good smell, good timing.","Cô hứa không kiểm tra từ vựng ở đây.","Một phần nhỏ... actually, hai phần.","English Club sắp ghé đó em.","Perfect, cho cô đơn ngẫu nhiên."], highRelationship:["Quầy mình đúng là favorite stop của cô."], fastService:["Excellent timing."], slowService:["No worries, cô chờ được."], wrongOrder:["Not quite right, mình thử lại nha."], rain:["Rainy day, đồ nóng là perfect."], exams:["Good luck không đủ, phải ngủ nữa nha."], graduation:["Keep in touch, tụi nhỏ nhớ quay lại."]
    }}),
    npc({ id:"anh-bon-ba-bay", name:"Anh 4:37", avatar:"./assets/characters/mystery.svg", ageRole:"Cựu học sinh bí ẩn", personality:"Kín tiếng, đúng giờ, tử tế", speakingStyle:"Ngắn, luôn nhìn đồng hồ", reason:"Trở lại nơi từng chờ người bạn cũ", runningJoke:"Xuất hiện gần đúng 4:37 và gọi tổ hợp lạ", arc:"Dần tiết lộ mình là cựu học sinh và giúp quầy có mái che", relations:["chu-sau","chi-hong"], favoriteFood:null, dislikedFood:null, preferredSauce:"sot-mix", patienceMultiplier:1.4, portionSizeWeight:"large", schedule:"late-afternoon", storyEvents:["mystery-1","mystery-2","mystery-reveal"], dialogue:{
      firstVisit:["Cho anh phần như hôm qua... à, hôm nay là lần đầu."], normal:["Bốn giờ ba mươi bảy.","Anh tới sớm một phút.","Vẫn tổ hợp ngẫu nhiên đó nhé.","Đừng hỏi sao anh nhớ giờ.","Chú Sáu vẫn còn làm ở đây à?","Khúc đường này thay đổi nhiều.","Mùi đồ chiên thì không đổi mấy.","Cho anh thêm sốt mix.","Hôm nay anh chỉ ghé nhanh.","Anh từng đứng chờ ở đây lâu lắm.","Biệt danh 4:37 nghe cũng được.","Chị Hồng đoán sai nghề anh rồi.","Một ngày nào đó anh kể.","Mưa xuống y như hồi đó.","Cảm ơn vì vẫn mở giờ này."], highRelationship:["Anh từng là học sinh ở đây. 4:37 là giờ bạn anh tan đội tuyển.","Mái che mới coi như quà của một khách quen."], fastService:["Vẫn kịp giờ."], slowService:["Anh từng chờ lâu hơn vậy nhiều."], wrongOrder:["Không sao, tổ hợp của anh vốn đã khó nhớ."], rain:["Ngày đó cũng mưa như vầy."], exams:["Hồi thi anh cũng ghé đúng giờ này."], graduation:["Có người rời trường rồi vẫn quay về."]
    }})
  ];

  /* Cast cleanup requested for the current edition: three students and half of
     the teacher roster are retired without breaking older save files. */
  const REMOVED_CHARACTER_IDS = new Set(["tram", "my", "gia-huy", "co-thao", "thay-phong", "thay-khoi"]);
  const characters = allCharacters.filter(function (character) { return !REMOVED_CHARACTER_IDS.has(character.id); });

  function stage(points) {
    if (points >= 40) return "BEST CUSTOMER";
    if (points >= 22) return "FRIEND";
    if (points >= 10) return "FAMILIAR";
    if (points >= 4) return "REGULAR";
    return "STRANGER";
  }

  function stageLabel(value) {
    return { "STRANGER":"Khách mới", "REGULAR":"Khách quen", "FAMILIAR":"Thân thuộc", "FRIEND":"Bạn của quầy", "BEST CUSTOMER":"Khách ruột" }[value] || "Khách mới";
  }

  function pickDialogue(character, context, save) {
    const pool = character.dialogue[context] && character.dialogue[context].length ? character.dialogue[context] : character.dialogue.normal;
    const key = character.id + ":" + context;
    const previous = Number(save.story.dialogueSeen[key]);
    let index = Math.floor(Math.random() * pool.length);
    if (pool.length > 1 && index === previous) index = (index + 1) % pool.length;
    save.story.dialogueSeen[key] = index;
    return pool[index];
  }

  function getById(id) { return characters.find(function (character) { return character.id === id; }); }

  function eligible(day, eventId) {
    const unlock = {
      khanh:1, nhan:1, trang:1, tran:1, tram:1, quy:1, an:2, duong:2, thuy:2, hoc:3, han:4, vu:3, my:3, "gia-huy":2,
      "chu-sau":1, "co-huong":2, "bac-tu":2, "co-lan":4, "thay-phong":4, "co-mai":4, "co-thao":5,
      "co-linh":4, tho:4, "thay-khoi":5, "thay-tung":5, "thay-minh":6, "chi-hong":7, "chu-thanh":6, "anh-bon-ba-bay":8
    };
    return characters.filter(function (character) {
      if (day < (unlock[character.id] || 1)) return false;
      if (character.id === "anh-bon-ba-bay") return day >= 8 && (eventId === "rain" || Math.random() < .18);
      return true;
    });
  }

  CVVH.Characters = { all: Object.freeze(characters), getById: getById, eligible: eligible, stage: stage, stageLabel: stageLabel, pickDialogue: pickDialogue };
})();
