(function () {
  "use strict";
  const CVVH = window.CVVH = window.CVVH || {};

  function npc(data) {
    const defaults = {
      ageRole:"Khách quen quanh quầy", personality:"Thân thiện", speakingStyle:"Tự nhiên", reason:"Ghé ăn xế",
      runningJoke:"", arc:"", relations:[], favoriteFood:null, dislikedFood:null, preferredSauce:null,
      patienceMultiplier:1, portionSizeWeight:"normal", schedule:"afternoon", storyEvents:[]
    };
    const value = Object.assign(defaults, data);
    value.relationship = { stranger:0, regular:4, familiar:10, friend:22, bestCustomer:40 };
    const normal = (value.dialogue && value.dialogue.normal) || ["Cho em một phần nha chị.","Hôm nay quầy đông ghê.","Mùi đồ chiên thơm quá chị."];
    value.dialogue = Object.assign({
      firstVisit:[normal[0]], normal:normal, highRelationship:["Quầy này thành chỗ quen của em rồi."],
      fastService:["Nhanh ghê chị."], slowService:["Em chờ được chị."], wrongOrder:["Hình như đơn này chưa đúng chị ơi."],
      rain:["Mưa mà có đồ nóng là đúng bài."], exams:["Tuần thi nên em cần nạp năng lượng."], graduation:["Sau này em vẫn ghé quầy nha chị."]
    }, value.dialogue || {});
    return Object.freeze(value);
  }

  const characters = [
    npc({ id:"khanh", name:"Khánh", avatar:"./assets/characters/khanh.svg", ageRole:"Học sinh mê ẩm thực", personality:"Vui vẻ, tự tin, mũm mĩm và cực kỳ nghiêm túc với đồ ăn", speakingStyle:"Hào hứng như nhà phê bình ẩm thực", reason:"Thử mọi món ở quầy", runningJoke:"Một phần lớn chỉ là màn khởi động", relations:["duong","an","chu-sau"], patienceMultiplier:1.45, portionSizeWeight:"huge", dialogue:{
      normal:["Hôm nay em giảm ăn. Cho phần lớn thôi.","Một xiên chỉ là lời chào.","Chị cứ chiên, chuyện số lượng để em lo.","Em tới kiểm tra chất lượng định kỳ.","Mùi này làm em quên luôn tiết sau.","Hôm nay quầy đạt chuẩn Khánh.","Bốn phần là giảm rồi chị.","Em đã chuẩn bị tinh thần cho khay lớn."],
      fastService:["Nhanh vậy? Em chưa kịp phân tích mùi thơm."], slowService:["Em kiên nhẫn được, miễn phần cuối đừng nhỏ."], wrongOrder:["Sai món không đáng sợ. Phần ít mới đáng sợ."]
    }}),
    npc({ id:"nhan", name:"Nhân", avatar:"./assets/characters/nhan.svg", ageRole:"Nữ du học sinh trao đổi từ Hong Kong", personality:"Điềm tĩnh, quan sát kỹ, hài khô", speakingStyle:"Tiếng Việt tốt, đôi lúc so sánh Việt Nam với Hong Kong", reason:"Khám phá đồ ăn đường phố Việt Nam", runningJoke:"Luôn cần thêm một mẫu thử trước khi kết luận", relations:["thay-tung"], patienceMultiplier:1.12, dialogue:{
      normal:["Ở Hong Kong cũng có fish ball, nhưng kiểu này khác.","Em cần thử thêm vài lần mới kết luận.","Hôm nay em thu thập thêm một mẫu dữ liệu.","Biên Hòa nóng hơn em tưởng, đồ ăn thì đáng thử hơn em tưởng.","Em gọi đây là nghiên cứu thực địa.","Em chưa kết luận đâu. Cần thêm mẫu."],
      fastService:["Dữ liệu lần này rất thuyết phục."], wrongOrder:["Kết quả không khớp đầu vào rồi chị."]
    }}),
    npc({ id:"trang", name:"Trang", avatar:"./assets/characters/trang.svg", ageRole:"Học sinh", personality:"Thẳng thắn, trách nhiệm, tỉnh táo", speakingStyle:"Rõ ràng nhưng thân thiện", reason:"Ghé cùng Quý và Trân", runningJoke:"Luôn biết hai bạn thân đang giấu gì", relations:["quy","tran","thuy"], patienceMultiplier:1.08, dialogue:{ normal:["Trân với Quý tới chưa chị?","Ba đứa em có group mà không ai đọc.","Hôm nay em ăn một mình. Chắc vậy.","Em tới lấy đồ trước khi hai đứa kia đổi ý.","Tuần này bài nhiều quá chị.","Quý mà nói còn một phút thì chị đừng tin."] }}),
    npc({ id:"tran", name:"Trân", avatar:"./assets/characters/tran.svg", ageRole:"Học sinh", personality:"Lém lỉnh, tinh ý, tình cảm", speakingStyle:"Nhanh, hay trêu bạn", reason:"Ghé ăn và cập nhật chuyện của hội bạn", runningJoke:"Bí mật tồn tại khoảng ba phút", relations:["quy","trang","thuy"], patienceMultiplier:1.05, dialogue:{ normal:["Lát Trang hỏi thì chị đừng nói em ăn trước nha.","Chuyện này đừng lên group nha chị.","Quý với Trang chưa tới đúng không?","Em mua mang về cho bạn nên không tính là ăn trước.","Em không giấu gì hết. Chị đừng hỏi.","Chị thấy hôm nay ai đáng nghi nhất?"] }}),
    npc({ id:"quy", name:"Quý", avatar:"./assets/characters/quy.svg", ageRole:"Học sinh", personality:"Vui tính, hơi hỗn loạn, hay chạy trễ", speakingStyle:"Nhanh và hay đổi chủ đề", reason:"Ghé ăn với Trang và Trân", runningJoke:"Lúc nào cũng còn đúng một phút", relations:["trang","tran","chu-sau"], patienceMultiplier:.82, dialogue:{ normal:["Chị làm nhanh, em còn đúng một phút!","Trang với Trân tới chưa chị?","Em không trễ, đồng hồ chạy sớm.","Cho em món cầm chạy được.","Hôm nay em tới sớm hơn hai giây.","Em định tiết kiệm tiền. Nhưng mai tiết kiệm."] }}),
    npc({ id:"an", name:"An", avatar:"./assets/characters/an.svg", ageRole:"Nam sinh đội bóng rổ", personality:"Năng lượng, kỷ luật, thân thiện", speakingStyle:"Gọn, khỏe khoắn", reason:"Ăn sau buổi tập bóng rổ", runningJoke:"Luôn giải thích phần lớn bằng lượng calo vừa đốt", relations:["khanh"], patienceMultiplier:1.02, portionSizeWeight:"large", dialogue:{ normal:["Chị làm phần lớn nha, em mới tập xong.","Hôm nay chạy muốn xỉu.","Em đốt calo rồi, giờ nạp lại thôi.","Trận tập hôm nay căng ghê chị.","Cho em phần đủ để hồi pin nha.","Em không gọi nhiều, em gọi đúng nhu cầu vận động."], fastService:["Nhanh như fast break luôn chị."], wrongOrder:["Pha này lệch rổ rồi chị."] }}),
    npc({ id:"duong", name:"Dương", avatar:"./assets/characters/duong.svg", ageRole:"Nam sinh IT", personality:"Năng lượng, vui tính, xã giao", speakingStyle:"Đùa công nghệ, hay hỏi hôm nay có bạn nào xinh ghé", reason:"Ăn xế và hóng chuyện vô hại", runningJoke:"Hỏi tình hình nhưng không phải tình hình cá viên", relations:["thuy","thay-tung","khanh"], patienceMultiplier:.98, portionSizeWeight:"normal", dialogue:{ normal:["Nay có bạn nào xinh ghé quán không chị?","Hôm nay tình hình sao chị? Không phải tình hình cá viên nha.","Có dữ liệu gì mới không chị?","Em tới ăn thôi nha. Thiệt.","Em đang restore system bằng đồ chiên.","Project chưa xong mà em vẫn phải ăn."], fastService:["Response time tốt đó chị."], wrongOrder:["Sai output rồi chị."] }}),
    npc({ id:"thuy", name:"Thủy", avatar:"./assets/characters/thuy.svg", ageRole:"Nam sinh IT, bạn cùng lớp Dương", personality:"Hiền, tốt bụng, siêu thích chị Thảo", speakingStyle:"Chân thành, dễ lúng túng khi bị trêu", reason:"Ăn xế và tìm mọi lý do để ghé chị Thảo", runningJoke:"Không ai tin em chỉ tới vì cá viên; ai cũng biết em thích chị Thảo", relations:["duong","trang","tran"], patienceMultiplier:1.18, dialogue:{ normal:["Chị Thảo hôm nay đẹp quá.","Chị ăn tối chưa? Em hỏi thiệt đó.","Em ghé vì nhớ— nhớ cá viên.","Tóc chị hôm nay khác một chút đúng không?","Mai chị có bán không? Em hỏi để... sắp lịch.","Em có thể phụ chị làm gì không? Em biết code.","Dương có qua chưa chị? Nó mà nói xấu em thì đừng tin.","Quán đông vậy chị có mệt không?"], highRelationship:["Em tới ăn hay tới gặp chị hả? ...Cả hai.","Chị cần gì cứ nhắn em nha. Em qua liền."], wrongOrder:["Không sao đâu chị, mình làm lại nha."] }}),
    npc({ id:"vu", name:"Vũ", avatar:"./assets/characters/vu.svg", ageRole:"Học sinh", personality:"Bình thường tự tin, riêng chủ đề Hân thì lúng túng", speakingStyle:"Tự nhiên cho tới khi hỏi Hân", reason:"Ăn xế và... kiểm tra xem Hân có ghé chưa", runningJoke:"Hân đâu rồi?", relations:["han","duong"], patienceMultiplier:1.03, dialogue:{ normal:["Hân đâu rồi chị?","Hân có ghé chưa chị?","Em tới ăn thôi. Mà Hân đâu rồi?","Em có hỏi Hân đâu... chưa kịp hỏi thôi.","Chị đừng nhìn em kiểu đó.","Nếu Hân tới thì... thôi, không có gì."] }}),
    npc({ id:"han", name:"Hân", avatar:"./assets/characters/han.svg", ageRole:"Học sinh", personality:"Bình tĩnh, thân thiện, tinh ý", speakingStyle:"Nhẹ nhàng, thỉnh thoảng trêu rất khẽ", reason:"Có câu chuyện riêng và cũng hay ghé quầy", runningJoke:"Biết nhiều hơn Vũ nghĩ", relations:["vu"], patienceMultiplier:1.12, dialogue:{ normal:["Hôm nay em muốn thử món khác.","Ở đây ồn mà dễ chịu ghê.","Nãy Vũ có ghé không chị?","Nó hỏi em chứ gì? Em biết mà.","Em tới vì đồ ăn nha chị, không liên quan ai hết.","Hôm nay em chỉ muốn ăn rồi về thôi." ] }}),
    npc({ id:"hoc", name:"Học", avatar:"./assets/characters/hoc.svg", ageRole:"Học sinh", personality:"Thông minh, vui tính, trì hoãn", speakingStyle:"Tỉnh bơ", reason:"Nạp năng lượng trước khi... bắt đầu học", runningJoke:"Tên là Học nhưng học sau khi ăn", relations:["trang"], patienceMultiplier:1, dialogue:{ normal:["Em đang nạp năng lượng để học.","Chị đừng hỏi em học chưa.","Ăn xong em học thiệt.","Em đang tối ưu lịch ôn.","Hôm nay em nghiêm túc. Mai thi.","Tên em là Học chứ đâu có nghĩa lúc nào cũng học."] }}),
    npc({ id:"phuoc-nguyen", name:"Phước Nguyên", avatar:"./assets/characters/phuoc-nguyen.svg", ageRole:"Học sinh học rất giỏi", personality:"Thông minh, hài hước, troll tỉnh", speakingStyle:"Nhanh, sắc, nói đùa mặt rất nghiêm túc", reason:"Giải lao có chiến lược", runningJoke:"Hai việc học giỏi và ăn cá viên không mâu thuẫn", relations:["anh-quan"], patienceMultiplier:1.08, dialogue:{ normal:["Chị, em vừa được điểm cao. Nên hôm nay em ăn bằng tiền của Anh Quân.","Hai việc học giỏi và ăn cá viên không mâu thuẫn.","Em đang giải lao có chiến lược.","Nếu Quân tới chị nói em chưa ghé nha.","Bài khó em giải được, chọn sốt mới khó.","Em không khoe điểm. Em cung cấp dữ kiện."], fastService:["Tối ưu ghê chị."], wrongOrder:["Đáp án này chắc bị lệch đề rồi chị."] }}),
    npc({ id:"anh-quan", name:"Anh Quân", avatar:"./assets/characters/anh-quan.svg", ageRole:"Học sinh", personality:"Thoải mái, lanh, biết đỡ miếng", speakingStyle:"Tự nhiên, phản đòn nhanh", reason:"Ghé cùng hoặc sau Phước Nguyên", runningJoke:"Luôn phải làm damage control cho bạn thân", relations:["phuoc-nguyen"], patienceMultiplier:1.06, dialogue:{ normal:["Chị đừng tin lời Nguyên.","Nguyên có tới chưa chị? Nó mới gửi em hình cá viên.","Em cảnh báo trước thôi, chưa biết nó bịa gì.","Hôm nay em trả tiền phần em thôi nha.","Chơi với Nguyên phải có kế hoạch dự phòng.","Nếu nó bảo em mời thì chị hỏi lại em trước."], fastService:["Được, lần này em tới trước Nguyên."], wrongOrder:["Chắc Nguyên đổi đề của em rồi."] }}),
    npc({ id:"thien-an", name:"Thiên Ân", avatar:"./assets/characters/thien-an.svg", ageRole:"Học sinh có vẻ ngoài hơi giang hồ", personality:"Cộc cằn ngoài miệng nhưng cực tốt bụng", speakingStyle:"Câu ngắn, thẳng", reason:"Ghé ăn rồi âm thầm giúp quầy", runningJoke:"Làm việc tốt xong luôn bảo không có gì", relations:[], patienceMultiplier:1.2, dialogue:{ normal:["Gì nhanh nhất chị làm cho em.","Cho phần. Nhiều chút.","Ghế lệch. Để em kê.","Mưa thì chị kéo đồ vô đi.","Không có gì. Em tiện tay thôi.","Con Homi đâu? Em hỏi vậy thôi."], fastService:["Ừ. Nhanh."], wrongOrder:["Không đúng. Làm lại được."] }}),
    npc({ id:"hoang-linh", name:"Hoàng Linh", avatar:"./assets/characters/hoang-linh.svg", ageRole:"Tay trống đội âm nhạc của trường", personality:"Năng lượng, nhịp nhàng, thân thiện", speakingStyle:"Hay chèn từ về nhịp và tempo", reason:"Ăn sau rehearsal", runningJoke:"Gõ nhịp lên bất cứ bề mặt nào", relations:[], patienceMultiplier:1.02, dialogue:{ normal:["Cốc cốc cốc— em đang giữ nhịp thôi chị.","Tối nay tụi em diễn đó chị.","Rehearsal xong em đói ngang một bài encore.","Quầy chị có tiếng chảo nghe cũng ra beat đó.","Em hứa không gõ lên quầy nữa. Chắc vậy.","Cho em món nào hợp tempo nhanh."], fastService:["Tempo đẹp."], slowService:["Hơi largo nha chị."], wrongOrder:["Pha này lệch nhịp rồi chị."] }}),
    npc({ id:"chu-sau", name:"Chú Sáu", avatar:"./assets/characters/chu-sau.svg", ageRole:"Bảo vệ trường hư cấu", personality:"Điềm đạm, quan sát giỏi", speakingStyle:"Nam Bộ nhẹ nhàng", reason:"Ghé đầu/cuối buổi", runningJoke:"Đoán chính xác ai sắp xuất hiện", relations:["khanh","quy"], patienceMultiplier:1.4, dialogue:{ normal:["Chút nữa Khánh tới cho coi.","Chiều coi bộ mưa à nghen.","Tụi nhỏ sắp tan rồi đó con.","Quầy hôm nay thơm dữ.","Chú ghé coi có cần phụ kéo bạt không."] }}),
    npc({ id:"co-huong", name:"Cô Hương", avatar:"./assets/characters/co-huong.svg", ageRole:"Phụ huynh", personality:"Thân thiện, dễ bắt chuyện", speakingStyle:"Tự nhiên", reason:"Chờ đón con", runningJoke:"Luôn nói chỉ đứng chờ rồi lại mua", patienceMultiplier:1.28, dialogue:{ normal:["Cô chỉ đứng chờ con thôi.","Thôi cho cô một phần.","Cho cô thêm phần mang về nữa.","Con cô chưa ra, cô ăn trước vậy.","Quầy đông ghê con."] }}),
    npc({ id:"chu-thanh", name:"Chú Thành", avatar:"./assets/characters/chu-thanh.svg", ageRole:"Phụ huynh", personality:"Nghiêm ngoài mặt, dễ mềm lòng", speakingStyle:"Chậm, chắc", reason:"Đón con", runningJoke:"Nói đồ chiên không tốt rồi gọi hai phần", patienceMultiplier:1.25, dialogue:{ normal:["Mấy món chiên ăn nhiều không tốt.","Cho chú hai phần.","Phần kia cho con chú. Phần này... cũng cho chú.","Chú nói ăn ít thôi mà tụi nhỏ không nghe.","Hôm nay chú ngoại lệ." ] }}),
    npc({ id:"tho", name:"Thơ", avatar:"./assets/characters/tho.svg", ageRole:"Nữ công an hư cấu tham gia kiểm tra an toàn thực phẩm", personality:"Chuyên nghiệp, bình tĩnh, thân thiện", speakingStyle:"Rõ, gọn", reason:"Ban đầu kiểm tra, sau thành khách quen", runningJoke:"Thảo cứ thấy chị là tự khai đủ giấy tờ", patienceMultiplier:1.3, dialogue:{ normal:["Chào em. Hôm nay chị tới ăn.","Dầu này dùng lâu rồi đó em.","Khu chế biến gọn đó.","Cho chị một phần. Không kiểm tra gì hôm nay.","Em đừng hoảng, chị chỉ ghé mua đồ."], wrongOrder:["Mình đối chiếu lại một lần nhé."] }}),
    npc({ id:"thay-minh", name:"Thầy Minh", avatar:"./assets/characters/thay-minh.svg", ageRole:"Hiệu trưởng hư cấu", personality:"Trang trọng nhưng hài khô", speakingStyle:"Điềm tĩnh", reason:"“Kiểm tra khu vực”", runningJoke:"Chỉ quan sát rồi cuối cùng gọi món", patienceMultiplier:1.35, dialogue:{ normal:["Thầy chỉ quan sát khu vực thôi.","...cho thầy một phần.","Hôm nay quầy hoạt động tốt.","Thầy không tham gia cạnh tranh thương mại.","Các em cứ tự nhiên. Thầy chỉ mua cá viên." ] }}),
    npc({ id:"co-lan", name:"Cô Lan", avatar:"./assets/characters/co-lan.svg", ageRole:"Phó hiệu trưởng hư cấu", personality:"Chính xác, có tổ chức", speakingStyle:"Ngắn, đúng giờ", reason:"Đặt phần cho giáo viên", runningJoke:"Luôn quay lại đúng số phút đã nói", patienceMultiplier:1.22, portionSizeWeight:"group", dialogue:{ normal:["Cô quay lại sau bảy phút.","Bảy phút rồi.","Cho cô phần này, đúng số lượng giúp cô.","Cô đang có bốn phút trống.","Hôm nay cô mua cho phòng giáo viên." ] }}),
    npc({ id:"thay-phong", name:"Thầy Phong", avatar:"./assets/characters/thay-phong.svg", ageRole:"Giáo viên Toán hư cấu", personality:"Logic, tỉnh, hài khô", speakingStyle:"Hay hỏi xác suất", reason:"Ăn nhẹ sau giờ dạy", runningJoke:"Muốn mọi nhận xét có con số", patienceMultiplier:1.25, dialogue:{ normal:["Xác suất món của thầy bị cháy là bao nhiêu?","Thấp là bao nhiêu phần trăm?","Giá tăng 5% thì khẩu phần có tăng không?","Thầy hỏi để biết thôi.","Hôm nay số khách khá đẹp." ] }}),
    npc({ id:"co-linh", name:"Cô Linh", avatar:"./assets/characters/co-linh.svg", ageRole:"Giáo viên tiếng Anh hư cấu", personality:"Vui vẻ, gần gũi", speakingStyle:"Thỉnh thoảng chèn cụm tiếng Anh ngắn", reason:"Ăn sau giờ dạy", runningJoke:"Spicy, but not too spicy", patienceMultiplier:1.24, dialogue:{ normal:["Spicy but not too spicy nha em.","How was your day? Thôi, order trước.","Hôm nay cô cần một phần quick and easy.","Good smell hôm nay đó.","Ăn xong cô còn chấm bài." ] }}),
    npc({ id:"thay-tung", name:"Thầy Tùng", avatar:"./assets/characters/thay-tung.svg", ageRole:"Giáo viên Tin hư cấu", personality:"Ít lời, hài khô", speakingStyle:"Ngắn", reason:"Ăn sau giờ coi phòng máy", runningJoke:"Code lỗi thì ăn xong sửa", relations:["duong","thuy"], patienceMultiplier:1.3, dialogue:{ normal:["Dương nói code lỗi.","Ăn xong sửa.","Thủy lại ở quầy hả?","Phòng máy hôm nay yên. Lạ.","Cho thầy một phần rồi nói tiếp." ] }}),
    npc({ id:"chi-hong", name:"Chị Hồng", avatar:"./assets/characters/chi-hong.svg", ageRole:"Chủ quầy kế bên", personality:"Cạnh tranh, thực tế, tốt bụng", speakingStyle:"Thẳng, vui", reason:"Nghiên cứu thị trường... rất thường xuyên", runningJoke:"Ăn quầy đối thủ và gọi đó là research", patienceMultiplier:1.18, dialogue:{ normal:["Chị đang nghiên cứu thị trường.","Khúc này khách khó lắm đó em.","Cho chị phần coi thử hôm nay consistency sao.","Chị ăn để kiểm tra thôi nha.","Đối thủ chứ có phải kẻ thù đâu." ] }}),
    npc({ id:"bac-tu", name:"Bác Tư", avatar:"./assets/characters/bac-tu.svg", ageRole:"Khách địa phương", personality:"Thoải mái, hiền", speakingStyle:"Chậm rãi", reason:"Ghé quầy chiều", runningJoke:"Luôn biết chuyện khu phố", patienceMultiplier:1.45, dialogue:{ normal:["Bán vui nghen con.","Chiều nay học sinh đông đó.","Cho bác phần nóng nha.","Khúc này hồi trước khác lắm.","Bác ngồi chút rồi đi." ] }}),
    npc({ id:"anh-bon-ba-bay", name:"Anh 4:37", avatar:"./assets/characters/mystery.svg", ageRole:"Cựu học sinh bí ẩn", personality:"Kín tiếng, đúng giờ", speakingStyle:"Ngắn", reason:"Trở lại nơi quen cũ", runningJoke:"Hay xuất hiện lúc 4:37", patienceMultiplier:1.4, portionSizeWeight:"large", dialogue:{ normal:["Bốn giờ ba mươi bảy.","Anh tới sớm một phút.","Khúc đường này thay đổi nhiều.","Mùi đồ chiên thì không đổi mấy.","Một ngày nào đó anh kể." ] }})
  ];

  function stage(points) {
    if (points >= 40) return "BEST CUSTOMER";
    if (points >= 22) return "FRIEND";
    if (points >= 10) return "FAMILIAR";
    if (points >= 4) return "REGULAR";
    return "STRANGER";
  }
  function stageLabel(value) { return {"STRANGER":"Khách mới","REGULAR":"Khách quen","FAMILIAR":"Thân thuộc","FRIEND":"Bạn của quầy","BEST CUSTOMER":"Khách ruột"}[value] || "Khách mới"; }
  function pickDialogue(character, context, save) {
    const pool = character.dialogue[context] && character.dialogue[context].length ? character.dialogue[context] : character.dialogue.normal;
    const key = character.id + ":" + context;
    const previous = Number(save.story.dialogueSeen[key]);
    let index = Math.floor(Math.random() * pool.length);
    if (pool.length > 1 && index === previous) index = (index + 1) % pool.length;
    save.story.dialogueSeen[key] = index;
    return pool[index];
  }
  function getById(id) { return characters.find(function (character) { return character.id === id; }); }
  function eligible(day, eventId) { return characters.filter(function (character) { return day >= 1 && (character.id !== "anh-bon-ba-bay" || day >= 8); }); }

  CVVH.Characters = { all:Object.freeze(characters), getById:getById, eligible:eligible, stage:stage, stageLabel:stageLabel, pickDialogue:pickDialogue };
})();
